### ISSUE TITLE
[Bug] IDW10502: An MsalUiRequiredException was thrown due to a challenge for the user

### ISSUE THREAD

**Issue by 1iveowl** [AzureAD/microsoft-identity-web#667] opened 2020-10-07 21:53 UTC
**Which version of Microsoft Identity Web are you using?**
Microsoft Identity Web 1.1.0, but I saw the same issue with version 1.0.0

**Where is the issue?**
* Web app
    * [ ] Sign-in users
    * [ ] Sign-in users and call web APIs
* Web API
    * [ ] Protected web APIs (validating tokens)
    * [ ] Protected web APIs (validating scopes)
    * [x ] Protected web APIs call downstream web APIs
* Token cache serialization
     * [ ] In-memory caches
     * [ ] Session caches
     * [ ] Distributed caches
* Other (please describe)

**Is this a new or an existing app?**
This is a new app or an experiment.

**Repro**

`startup.cs`:
```csharp
services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
    .AddMicrosoftIdentityWebApi(Configuration)
    .EnableTokenAcquisitionToCallDownstreamApi()
    .AddMicrosoftGraph(Configuration.GetSection("GraphApi"))
    .AddInMemoryTokenCaches();
```

`appsettings.json`
```json
...
  "AzureAD": {
    "Instance": "https://login.microsoftonline.com/",
    "Domain": "{domain}",
    "ClientId": "{client id}",
    "TenantId": "{tenant id}",
    "Audience": "api://{application id}",
    "ClientSecret": "{secret key}",
  },
  "GraphApi": {
    "BaseUrl": "https://graph.microsoft.com/v1.0",
    "Scopes": "Application.Read.All Application.ReadWrite.All Directory.Read.All Directory.ReadWrite.All"
  }, 
...
```

controller: 
```csharp
[HttpPost]
public async Task<string> Post()
{
    var applications = await _graphServiceClient.Applications
        .Request()
        .GetAsync();

    return applications.Count.ToString();
}
```

**Expected behavior**
Access to list of applications in Microsoft Graph.

I can generate an application token manually using Postman, which looks like the following, confirming that the configuration of the Application is correct in Azure AD.:

```json
[...more json]
{
  "aud": "https://graph.microsoft.com",
  "iss": "https://sts.windows.net/{tenant id}/",
  "iat": 1602055659,
  "nbf": 1602055659,
  "exp": 1602059559,
  "aio": "[...]",
  "app_displayname": "My app",
  "appid": "{App id guid}",
  "appidacr": "1",
  "idp": "https://sts.windows.net/{tenant id}/",
  "idtyp": "app",
  "oid": "{guid}",
  "rh": "[...]",
  "roles": [
    "Application.ReadWrite.All",
    "Directory.ReadWrite.All",
    "Directory.Read.All",
    "Application.Read.All"
  ],
  "sub": "{guid}",
  "tenant_region_scope": "EU",
  "tid": "{tenant id}",
  "uti": "[...]",
  "ver": "1.0",
  "xms_tcdt": 1597308440
}.[Signature]
```

**Actual behavior**
I get this exception exception when running the Post controller. 

> Status Code: 0
Microsoft.Graph.ServiceException: Code: generalException
Message: An error occurred sending the request.
>  ---> Microsoft.Identity.Web.MicrosoftIdentityWebChallengeUserException: IDW10502: An MsalUiRequiredException was thrown due to a challenge for the user. See https://aka.ms/ms-id-web/ca_incremental-consent. 
>  ---> MSAL.NetCore.4.19.0.0.MsalUiRequiredException: 
> 	ErrorCode: user_null
> Microsoft.Identity.Client.MsalUiRequiredException: No account or login hint was passed to the AcquireTokenSilent call.
>    at Microsoft.Identity.Client.AcquireTokenSilentParameterBuilder.Validate()
>    at Microsoft.Identity.Client.AbstractAcquireTokenParameterBuilder`1.ValidateAndCalculateApiId()
>    at Microsoft.Identity.Client.AbstractClientAppBaseAcquireTokenParameterBuilder`1.ExecuteAsync(CancellationToken cancellationToken)
>    at Microsoft.Identity.Client.AbstractAcquireTokenParameterBuilder`1.ExecuteAsync()
>    at [... etc. ...]

**Comment by jmprieur** [comment] 2020-10-08 09:30
@1iveowl this is because the tenant admin needs to provide admin consent to your web API for the scopes you want to use. 
Did you read the following tutorial? https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/tree/master/2.%20Web%20API%20now%20calls%20Microsoft%20Graph

**Comment by 1iveowl** [comment] 2020-10-08 09:33
> @1iveowl this is because the tenant admin needs to provide admin consent to your web API for the scopes you want to use.
> Did you read the following tutorial? https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/tree/master/2.%20Web%20API%20now%20calls%20Microsoft%20Graph

As far as I can tell Concent is already granted. I even added it both for Application and Delegated:

![Concent](https://user-images.githubusercontent.com/12871120/95441081-fc9fc300-0959-11eb-8e4c-820a7472dd65.jpg)

**Comment by jmprieur** [comment] 2020-10-08 09:39
@1iveowl 
- did you do things incrementally in a dev project? (adding scopes after you had tested).if so, you might want to delete your token cache in the client application (or signout and re-sign in).
- did you configure the KnownClientApplication property: https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/tree/master/2.%20Web%20API%20now%20calls%20Microsoft%20Graph#configure-known-client-applications-for-service-todolistservicems-identity-dotnet-native-aspnetcore-v2 ?
- are you using a user from the same tenant as the one you created the app? (is it a multi-tenant app)

Otherwise if you think that can happen in prod, you should have the Web API emit a www-authenticate header, and the client needs to process it. See https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/tree/master/2.%20Web%20API%20now%20calls%20Microsoft%20Graph#handling-required-interactions-with-the-user-dynamic-consent-mfa-etc for details.

I know that this is a lot of things to read, but this scenario is a bit complicated ...

**Comment by 1iveowl** [comment] 2020-10-08 13:03
> * did you do things incrementally in a dev project? (adding scopes after you had tested).if so, you might want to delete your token cache in the client application (or signout and re-sign in).

How do I do this? The app is authenticating using a secret. (note: I've updated appsettings.json in my initial post to reflect this, since I had omitted this by mistake). 

I was under the assumption that the application would go request an application access token, whenever it needs it. Or am I misunderstanding, what is being configured here?: 

```csharp
services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
    .AddMicrosoftIdentityWebApi(Configuration)
    .EnableTokenAcquisitionToCallDownstreamApi()
    .AddMicrosoftGraph(Configuration.GetSection("GraphApi"))
    .AddInMemoryTokenCaches();
```

> * did you configure the KnownClientApplication property: https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/tree/master/2.%20Web%20API%20now%20calls%20Microsoft%20Graph#configure-known-client-applications-for-service-todolistservicems-identity-dotnet-native-aspnetcore-v2 ?

No. For my test set-up, no authentication/authorization is required for the client. The API has anonymous access. 

I was under the assuming that the controller would be running in the context of itself, when trying to execute the code for connecting to Microsoft Graph - i.e. obtaining a an application access token using the secret key I've added to appsettings.json for section AzureAD.

> * are you using a user from the same tenant as the one you created the app? (is it a multi-tenant app)
> 
> Otherwise if you think that can happen in prod, you should have the Web API emit a www-authenticate header, and the client needs to process it. See https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/tree/master/2.%20Web%20API%20now%20calls%20Microsoft%20Graph#handling-required-interactions-with-the-user-dynamic-consent-mfa-etc for details.

Since I'm using application access tokens here, there's not suppose to be any user interaction.

**Comment by 1iveowl** [comment] 2020-10-08 13:55
Hmmm. I feel like I’m missing something basic.

How do I debug what happens here:

```csharp

services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
    .AddMicrosoftIdentityWebApi(Configuration)
    .EnableTokenAcquisitionToCallDownstreamApi()
    .AddMicrosoftGraph(Configuration.GetSection("GraphApi"))
    .AddInMemoryTokenCaches();
```

... when this controller/api endpoint is called:

```csharp

HttpPost]
public async Task<string> Post()
{
    var applications = await _graphServiceClient.Applications
        .Request()
        .GetAsync();

    return applications.Count.ToString();
}

```

**Comment by jmprieur** [comment] 2020-10-09 12:08
Oh I see. so:
- your web API is anonymous
- and you want to call the Graph on behalf of the application itself, not on behalf of the user. 

This is possible, but not fully automatic today. We have a feature request to make that happen in a nicer way: https://github.com/AzureAD/microsoft-identity-web/issues/654

To have it work in you case, you could get inspired by the  [ASP.NET Core Graph web hooks](https://github.com/microsoftgraph/aspnetcore-webhooks-sample/blob/52cb9fcdb5c962928538766e792916745fc3b999/src/GraphWebhooks-Core/Controllers/NotificationController.cs#L172-L176) sample where the GraphServiceClient can only be used for delegated scopes:

**Comment by jmprieur** [comment] 2020-10-09 12:08
Proposing to close as a duplicate of #654

**Closed** 2020-10-09 12:34 UTC
Labels: duplicate, external, question
