### ISSUE TITLE
Intermittent issue observed BlazorServer : AADSTS54005: OAuth2 Authorization code was already redeemed, please retry with a new valid code or use an existing refresh token

### ISSUE THREAD

**Issue by virajasawant06** [AzureAD/microsoft-identity-web#2621] opened 2024-01-03 06:36 UTC
### Microsoft.Identity.Web Library

Microsoft.Identity.Web.UI

### Microsoft.Identity.Web version

2.16.0

### Web app

Sign-in users and call web APIs

### Web API

Protected web APIs call downstream web APIs

### Token cache serialization

In-memory caches

### Description

The application gives intermittent issue as given below:Upon restarting the application the issue is not seen,

AADSTS54005: OAuth2 Authorization code was already redeemed, please retry with a new valid code or use an existing refresh token. Trace ID: 2492f1a9-288d-41c5-a2af-f571a5fe8e01 Correlation ID: c4211dbf-22b6-4fca-82d2-97a269d4db9f Timestamp: 2023-11-27 11:11:01Z

**Hosting Details:**
Hosting is done using Azure app service. The app service plans are hosted in East Asia region with P1V2 tier.
This issue is seen in all the environments except QA environment. We are actively using all environments (DEV, QA, UAT & Prod). 

**Application Details:**
Web App : Blazor Server , .net 6.0
API App :  .net 6.0

**Dependencies and other related packages with versions for Web App**

<img width="212" alt="MicrosoftTeams-image" src="https://github.com/AzureAD/microsoft-identity-web/assets/155515418/1aef2b95-d54a-43cb-bfb1-330c4c1b3b87">

### Reproduction steps

<img width="651" alt="MicrosoftTeams-image (1)" src="https://github.com/AzureAD/microsoft-identity-web/assets/155515418/6a7353f8-b4b4-421f-b3e0-a811e4b9e308">
[
<img width="1407" alt="MicrosoftTeams-image (2)" src="https://github.com/AzureAD/microsoft-identity-web/assets/155515418/863bd580-fa73-49ea-8879-00156dac8b7f">
](url)

This behavior is intermittent in occurrence.

### Error message

MsalUiRequiredException: AADSTS54005: OAuth2 Authorization code was already redeemed, please retry with a new valid code or use an existing refresh token. Trace ID: 15901651-997b-48a6-b621-73383b8e0800 Correlation ID: 4102fcdf-a767-46e9-888b-cd5660dbca65 Timestamp: 2023-12-21 05:13:34Z

### Id Web logs

[query_data (4).csv](https://github.com/AzureAD/microsoft-identity-web/files/13816199/query_data.4.csv)

### Relevant code snippets

```csharp
builder.Services.AddMicrosoftIdentityWebAppAuthentication(builder.Configuration, "AzureAdWeb")
                .EnableTokenAcquisitionToCallDownstreamApi() 
                .AddInMemoryTokenCaches();
 
builder.Services.AddControllersWithViews()
        .AddMicrosoftIdentityUI();
 
builder.Services.AddAuthorization(options =>
{
    // By default, all incoming requests will be authorized according to the default policy
```

### Expected behavior

Application should not give the intermittent issue which we are facing currently at random occurrence.

**Comment by jennyf19** [comment] 2024-01-03 17:32
@virajasawant06 Does this repro with net8.0?

**Comment by virajasawant06** [comment] 2024-01-04 06:31
> @virajasawant06 Does this repro with net8.0?
Not sure about it as we have not migrated code to .net8.0

**Comment by westin-m** [comment] 2024-01-10 17:42
Hey @virajasawant06, we're not able to reproduce your issue. Could you please send us a basic blazorserver setup that does repro it? We will use our own test credentials. Thank you!

**Comment by virajasawant06** [comment] 2024-01-16 14:02
> Hey @virajasawant06, we're not able to reproduce your issue. Could you please send us a basic blazorserver setup that does repro it? We will use our own test credentials. Thank you!

Hi, Could you please let us know the exact components/files which are required to repro this issue ? As our code base is pretty much customized we wont be able to provide the existing code.
We are using blazor server app with .net 6.0 and following are the package versions

<img width="228" alt="MicrosoftTeams-image (4)" src="https://github.com/AzureAD/microsoft-identity-web/assets/155515418/6ae65940-ea31-4092-87b6-8fdbdfaccceb">


<img width="318" alt="MicrosoftTeams-image (5)" src="https://github.com/AzureAD/microsoft-identity-web/assets/155515418/e8c8c83c-f472-4c55-9b0e-3675ad5fd1f0">

**Comment by westin-m** [comment] 2024-01-16 22:58
> Hi, Could you please let us know the exact components/files which are required to repro this issue ? As our code base is pretty much customized we wont be able to provide the existing code. We are using blazor server app with .net 6.0 and following are the package versions

This is the [developer app](https://github.com/AzureAD/microsoft-identity-web/tree/master/tests/DevApps/blazorserver-calls-api) we are using. Can you help us understand what needs to change, perhaps in `Startup.cs` or elsewhere, to reproduce your issue?

**Comment by jennyf19** [comment] 2024-01-26 02:35
@virajasawant06 we cannot move forward without a repro from you, as we cannot repro it ourselves. Thanks.

**Comment by virajasawant06** [comment] 2024-01-30 09:43
Hi,
Attaching zip file of the project which you can repro
[Uploading Sample_Project.zip…]()

**Comment by virajasawant06** [comment] 2024-01-30 09:43
[Sample_Project.zip](https://github.com/AzureAD/microsoft-identity-web/files/14095766/Sample_Project.zip)

**Comment by virajasawant06** [comment] 2024-02-09 06:19
Hi @jennyf19 any update after we have sent the sample project ?

**Comment by bgavrilMS** [comment] 2024-12-12 12:31
We believe this is related to a bug in .NET, see issue https://github.com/AzureAD/microsoft-identity-web/issues/2612 ... upgrading to the latest .NET and latest Id.Web should solve it. Closing this as duplicate. 

Pls let us know if there is still a problem, and we will reopen.

**Closed by bgavrilMS** 2024-12-12 12:31 UTC
Labels: blocked, needs more info, css, blazor-server
