### ISSUE TITLE
Multi tenant sign-in not working from 2.17.2 and onwards

### ISSUE THREAD

**Issue by shareonline** [AzureAD/microsoft-identity-web#2741] opened 2024-04-03 21:55 UTC
### Microsoft.Identity.Web Library

Microsoft.Identity.Web

### Microsoft.Identity.Web version

2.17.2

### Web app

Sign-in users

### Web API

Protected web APIs call downstream web APIs

### Token cache serialization

In-memory caches

### Description

When using the "organizations" part in both tenantid, and authority for my multitenant application, i get the following error logging in:
Cannot use WithTenantId(tenantId) in the application builder, because the authority Generic doesn't support it.

When i downgrade to 2.17.1 the same code works again.

Maybe i am doing something wrong, but most of the documentation i can find is pretty old, and not really describing my multi-tenant scenario.

### Reproduction steps

when setting up .AddMicrosoftIdentityWebApp(options =>
                {
                    builder.Configuration.GetSection("AzureAd").Bind(options);
                    options.Authority = "https://login.microsoftonline.com/organizations";
                    options.TenantId = "organizations";
                })
                .EnableTokenAcquisitionToCallDownstreamApi()
                
I experience the error and no users can sign in. 

### Error message

Happens onRemoteFailure event:
Cannot use WithTenantId(tenantId) in the application builder, because the authority Generic doesn't support it.

### Relevant code snippets

```csharp
builder.Services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
                .AddMicrosoftIdentityWebApp(options =>
                {
                    builder.Configuration.GetSection("AzureAd").Bind(options);
                    options.Authority = "https://login.microsoftonline.com/organizations";
                    options.TenantId = "organizations";
                })
                .EnableTokenAcquisitionToCallDownstreamApi()
                .AddMicrosoftGraph(graphBaseUrl: "https://graph.microsoft.com/v1.0", initialScopes)
                .AddInMemoryTokenCaches(options =>
                {
                    options.AbsoluteExpirationRelativeToNow = new TimeSpan(15, 0, 0, 0);
                });
```

### Expected behavior

Sign user in on the multitenant endpoint in MSAL and return with a validated token.

**Comment by jmprieur** [comment] 2024-04-04 01:10
Thanks @shareonline for the feedback. This is a regression indeed.

As a workaround: do you mind replacing:

```csharp
options.Authority = "https://login.microsoftonline.com/organizations";
```

by

```csharp
options.Instance = "https://login.microsoftonline.com/";
```

Alternatively, setting the authority to "https://login.microsoftonline.com/organizations/v2.0", and not setting the tenant should also work.

```diff
 .AddMicrosoftIdentityWebApp(options =>
                {
                    builder.Configuration.GetSection("AzureAd").Bind(options);
-                    options.Authority = "https://login.microsoftonline.com/organizations/";
+                    options.Authority = "https://login.microsoftonline.com/organizations/v2.0";
-                    options.TenantId = "organizations";
                })
```

**Comment by jmprieur** [comment] 2024-04-04 02:09
P2 as there is a documented workaround (and we don't advise to use "Authority" for Entra ID (we do for Entra External IDs)

**Comment by shareonline** [comment] 2024-04-04 10:32
`options.TenantId = "organizations";
options.Instance = "https://login.microsoftonline.com/";`

This seems to work! 👌

The authority for Entra external IDs is needed in my case. Should the workaround then be to only use the authority, or everything together?
I'm curious as to why the authority isn't recommended?

**Comment by ntwilson** [comment] 2024-04-09 18:45
The same workaround works for me 🎉. Our tenant ID is "common" instead of "organizations"

**Comment by jennyf19** [comment] 2024-08-21 02:02
closing as answered

**Closed by jennyf19** 2024-08-21 02:02 UTC
Labels: bug, P2, answered, regression:entra
