### ISSUE TITLE
Multiple Authentication Methods

### ISSUE THREAD

**Issue by arcusic** [AzureAD/microsoft-identity-web#580] opened 2020-09-15 16:25 UTC
**Which version of Microsoft Identity Web are you using?**
0.4.0-preview

**Where is the issue?**
Attempting to build a web application that incorporates AAD Single Sign On, but also has a independent URL that can be used for local accounts in our internal database. Authentication against our local db username and password are successful, but after successfully authenticating against our local database, the following appears in the output.

```
Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler: Information: OpenIdConnect was not authenticated. Failure message: Not authenticated
Microsoft.AspNetCore.Authorization.DefaultAuthorizationService: Information: Authorization failed. These requirements were not met:
DenyAnonymousAuthorizationRequirement: Requires an authenticated user.
Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler: Information: AuthenticationScheme: OpenIdConnect was challenged.
```

**Is this a new or an existing app?**
b. The app is in production and I haven't upgraded Microsoft Identity Web, but started seeing this issue.

Is there any way to obtain authentication from our local db and not have OpenIDConnect come up?

**Edit:** Just to add some clarification, our secondary authentication is based off of cookie authentication.

**Comment by arcusic** [comment] 2020-09-16 23:47
@jmprieur Do you need any additional information or was that detailed enough? Honestly this was the first time I have opened an issue on GitHub.

Secondly, I was just curious where something like this would fall on the roadmap for development since it a new scenario.

Thanks for your time!

**Comment by jmprieur** [comment] 2020-09-18 10:35
@arcusic : do you agree that this is a duplicate of https://github.com/AzureAD/microsoft-identity-web/issues/133 ?

**Comment by arcusic** [comment] 2020-09-18 11:38
@jmprieur It's similar, but I would not necessarily call it a duplicate. Here is a sample of our source code for review.

Given that we are trying to support multiple authentication scenarios (Disabled, AAD, and Okta -- granted only one can be chosen at a time). The intent is so that if you have AAD our back door using cookie authentication would still be functional and give us authorization.

**Snippet from Startup.cs**

**Scenario 1: Normal Internal Database Authentication**
```
if (Configuration["SSOProvider:Provider"] == "DISABLED" || Configuration["SSOProvider:Provider"] == null)
            {
                services.AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme)
                    .AddCookie(options =>
                    {
                        options.LoginPath = "/Login/";
                        options.LogoutPath = "/Login/Logout";
                        options.AccessDeniedPath = "/Login/Denied";
                        options.Cookie.HttpOnly = true;
                        options.Cookie.IsEssential = true;
                        options.Cookie.Name = "LoggedIn";
                        options.SlidingExpiration = true;
                        options.ExpireTimeSpan = TimeSpan.FromMinutes(Convert.ToDouble(Configuration["SessionExpirationTimeout"]));
                        options.EventsType = typeof(CustomCookieAuthenticationEvents);
                    });
            }
```

**Scenario 2: Microsoft.Identity.Web**
Part 1:
```
else if (Configuration["SSOProvider:Provider"] == "AZUREAD")
            {
                services.Configure<CookiePolicyOptions>(options =>
                {
                    // This lambda determines whether user consent for non-essential cookies is needed for a given request.
                    options.CheckConsentNeeded = context => true;
                    options.MinimumSameSitePolicy = SameSiteMode.Unspecified;
                    // Handling SameSite cookie according to https://docs.microsoft.com/en-us/aspnet/core/security/samesite?view=aspnetcore-3.1
                    options.HandleSameSiteCookieCompatibility();
                });

                services.AddOptions();

                services.AddMicrosoftIdentityWebAppAuthentication(Configuration, "AzureADConfiguration")
                        .EnableTokenAcquisitionToCallDownstreamApi(new string[] { Constants.ScopeUserRead })
                        .AddInMemoryTokenCaches();

                // Add APIs
                services.AddGraphService(Configuration);
                services.AddHttpClient<IArmOperations, ArmApiOperationService>();
            }
```
Part 2:
```
if (Configuration["SSOProvider:Provider"] == "AZUREAD")
            {
                services.AddMvc(options =>
                {
                    var policy = new AuthorizationPolicyBuilder()
                        .RequireAuthenticatedUser()
                        .Build();
                    options.Filters.Add(new AuthorizeFilter(policy));
                    options.Filters.Add(new AutoValidateAntiforgeryTokenAttribute());
                }).AddMicrosoftIdentityUI();
            }
            else
            {
                services.AddMvc(options =>
                {
                    var policy = new AuthorizationPolicyBuilder()
                        .RequireAuthenticatedUser()
                        .Build();
                    options.Filters.Add(new AuthorizeFilter(policy));
                    options.Filters.Add(new AutoValidateAntiforgeryTokenAttribute());
                });
            }
```

As you can see in our code, we're not using the .AddAuthentication in our attempt here, but the new .AddMicrosoftIdentityWebAppAuthentication function.

The problem that we run into here, is that we're finding that when going down our AAD scenario, we cannot add our cookie scheme because a cookie scheme already exists -- okay, maybe it's using the defaults and we don't need to worry. But then when we authenticate successfully, we are not able to obtain authorization so OpenIDConnect is challenged.

What would be ideal is if there was a way where we could specify that additional cookie method (shown above as an example for how we have it configured when AAD is not involved) so we can have that secondary login for internal accounts (eg. accounts that do not exist within the customer's directory (our support account, and additional people they want to have access without creating within their AAD environment.).


@jmprieur let me know what your thoughts are as you're definitely more familiar with the functions of the code than I am. If needed, I could privately send you our startup.cs file so you can review it in full. My inital reaction is that given we're using two different methods to obtain our goals, this is not a duplicate but an additional request, but I do not know how the inner workings of AddMicrosoftIdentityWebAppAuthentication so I figure you'd be a good judge based off of our code snippets.

**Comment by arcusic** [comment] 2020-10-01 14:09
@jmprieur Just wanted to follow up to see if you needed anymore info.

**Comment by jennyf19** [comment] 2021-05-25 20:44
@arcusic I believe this is enabled in 1.11 release, which allows for multiple [auth schemes](https://github.com/AzureAD/microsoft-identity-web/wiki/multiple-authentication-schemes) .

**Closed by jennyf19** 2021-05-25 20:44 UTC
Labels: duplicate
