### ISSUE TITLE
[Question] RequiredScope doesn't work (for web APIs called by daemon apps)

### ISSUE THREAD

**Issue by Anakael** [AzureAD/microsoft-identity-web#1571] opened 2021-12-30 16:15 UTC
**Which version of Microsoft Identity Web are you using?**

1.21.1

**Where is the issue?**
* Web API
    * [ ] Protected web APIs (validating scopes)

**Is this a new or an existing app?**

This is a new app or an experiment.

**Repro**

```csharp
[Route("api/[controller]")]
    [ApiController]
    [Authorize]
    public class SomeController : ControllerBase
    {
        [RequiredScope("myScopeName")]
        public async Task CreateSomething()
        {
              return Task.CompletedTask();
        }
    }
```

**Expected behavior**

Request finished with 403 code when pass scope `myScopeNameM2M`.

**Actual behavior**

Request finishes with 200 code

**Additional context / logs / screenshots / link to code**

```csharp
HttpContext.VerifyUserHasAnyAcceptedScope("myScopeName");
```
Works as expected.

**Comment by jennyf19** [comment] 2021-12-31 17:41
@Anakael I cannot repro:
<img width="1230" alt="image" src="https://user-images.githubusercontent.com/19942418/147834282-f9b82f34-6c6d-452c-8cc7-8508c0818a1e.png">

Can you share what you have in your Startup.cs? Thanks.

**Comment by Anakael** [comment] 2021-12-31 21:04
I did nothing special for it. Did I miss something?

**Comment by jennyf19** [comment] 2021-12-31 23:28
I would need more information from your Startup.cs. Do you have the same content as when you do `dotnet new webapi --auth SingleOrg`?

**Comment by spacattac** [comment] 2022-01-05 16:52
I've run into this issue as well, repro'd in 2 different projects.  What's interesting is it works/doesn't work as follows:

- **works**:  for access_tokens that are on-behalf-of-the-user via the authorization_code flow the RequiredScope attrib is working as expected
- **doesn't work**:  for access_tokens via client_credentials flow the RequiredScope attribute does not work (should return Forbidden when scope is missing), but using "HttpContext.VerifyUserHasAnyAcceptedScope(scopeRequiredByApi);" does work

https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-protected-web-api-verification-scope-app-roles?tabs=aspnetcore

So for now i'm using the VerifyUserHasAnyAcceptedScope method but would prefer to use the attribute

**Comment by jmprieur** [comment] 2022-01-05 17:54
Thanks for the explanation, @spacattac. This is by design (and to follow the protocol), but I realize that the design might not be very good, so I'm tempted to start a discussion with the group to simplify things

What happens is:
- Web APIs called on behalf of users need to verify the Scopes.
- Web APIs called on behalf of an app (a daemon app) need to verify app roles

But from the point of view of the client app, in both cases you request scopes (you are exposed to app roles when you do the app registration though).

This is all explained in [Protected web API: Verify scopes and app roles](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-protected-web-api-verification-scope-app-roles?tabs=aspnetcore)

**Comment by spacattac** [comment] 2022-01-05 18:16
Thanks @jmprieur .  i had read that msft docs link and i didn't really understand why the daemon app couldn't/wouldn't use the scope the same way and didn't understand what an app role is/was.  in reading more about Azure AD last night i did learn about the app registration and that app role designation is part of that registration.  that explains why i didn't/don't really know what it is - i'm not actually using Azure AD and instead am using Okta for OIDC+OAuth and the daemon app registration doesn't have an app role.  i can use Access Policies on the Okta auth server to grant the scopes to an app using client_credentials just like i can to an app acting on behalf of the user with authorization_code flow.

**Comment by jmprieur** [comment] 2022-01-05 18:28
Thanks for the explanation, @spacattac. 
`RequiredScopes` just [checks](https://github.com/AzureAD/microsoft-identity-web/blob/7b62b3dcc3861c4a0eca1b8561b0bdaec32c1977/src/Microsoft.Identity.Web/Policy/ScopeAuthorizationRequirement.cs#L41) at the `scp` or `http://schemas.microsoft.com/identity/claims/scope` claims. If Okta generates these, you should be good.

**Comment by spacattac** [comment] 2022-01-05 18:30
Thanks @jmprieur - yes, okta does generate the scope (scp) claim.  i don't understand why the call to HttpContext.VerifyUserHasAnyAcceptedScope(scopeRequiredByApi); works for me but [RequiredScopes(scopeRequiredByApi)] does not.  It seems to me there should be parity with these.

**Comment by jmprieur** [comment] 2022-01-05 18:37
I guess we'd need to see the structure of the token to understand this question? Are you using app.UseAuthorization? Did you customize the Authorization policies?

**Comment by spacattac** [comment] 2022-01-05 19:16
@jmprieur i'll grab some code and/or screen snippets to share/show ...

**Comment by spacattac** [comment] 2022-01-05 19:31
here's a snippet of scope check working as expected via the method but not the attribute.
 
![image](https://user-images.githubusercontent.com/101247/148276933-af6a0c8e-dc98-4f75-b997-27c31e8c2c20.png)

i am using app.UseAuthorization.  and in this project i do have 1 policy added but it's not used in the endpoint/method in this example.  also, the other project where i've repro'd this same behavior does not have any additional policies.

`            services.AddAuthorization(options =>
            {
                options.AddPolicy("AccessPersonPolicy", policy =>
                    policy.Requirements.Add(new IsAnAccessPersonRequirement()));
            });
`

**Comment by jmprieur** [comment] 2022-01-06 04:48
@spacattac : in the claims, the scope provided by Okta (item 7) has a value "access_token", whereas you want "documents.read". That's the reason.

**Comment by spacattac** [comment] 2022-01-06 14:47
@jmprieur - not exactly .... what i'm showing you above is i've intentionally left out the documents.create scope and i'm showing you how the [RequiredScopes("documents.create")] attribute did NOT block the call yet the VerifyUserHasAnyAcceptedScope("documents.create") DID block and returns Forbidden.  why is there not parity between these two?

**Comment by Pieter-1337** [comment] 2022-01-30 12:18
same issue here I have an access_token which I retieve through a Client from AD, then the client calls my WebAPI.

Currently my access_token has a "scp" attribute of "access_api" however when I add an [RequiredScope("access_api_admin")] decorator on a controller action (controller has [Authorize]) and I call the endpoint with the "access_api" scope the action gets executed.

Expected behavior would be an Unauthorized..., yet I am gettin the data which I should not be getting...

The token
![image](https://user-images.githubusercontent.com/24230642/151699255-3e9c6047-8763-43ca-adc2-bdcdbd570f86.png)

The endpoint with requiredScope "access_api_admin"
![image](https://user-images.githubusercontent.com/24230642/151699289-b9029a4b-2b38-4218-ba07-39b1a5cfbc19.png)

I feel this should block the request I am making with my access_token since the scope "access_api_admin" is not present in the token...

**Comment by gurry** [comment] 2022-03-15 06:27
RequiredScope used to work as expected here until version 1.17.0 of Microsoft.Identityt.Web. It got broken in 1.18.0. See these issues: https://github.com/AzureAD/microsoft-identity-web/issues/1609 https://github.com/AzureAD/microsoft-identity-web/issues/1002

**Comment by jmprieur** [comment] 2022-08-21 19:36
Closing this one:
- We released RequiredScopeOrAppPermissionAttribute in Microsoft.Identity.Web [1.25.0](https://github.com/AzureAD/microsoft-identity-web/releases/tag/1.25.0)
- @gurry : you are right, it requires to use app.AddAuthorization(). However, AddRequiredScopeAuthorization is called in  AddMicrosoftIdentityWebApi. Did you use that method?

**Closed by jmprieur** 2022-08-21 19:36 UTC
Labels: question, Answered

**Comment by gurry** [comment] 2022-08-24 04:14
@jmprieur Yes, I peeked inside Microsoft's code and saw `'AddRequiredScopeAuthorization()` being used there and simply mimicked that. It may well have been `AddMicrosoftIdentityWebApi()` that I peeked into (don't exactly remember now).
