### ISSUE TITLE
[Feature Request] Automatically retrieve additional claims from UserInfo Endpoint

### ISSUE THREAD

**Issue by m-hicks-OH** [AzureAD/microsoft-identity-web#872] opened 2021-01-14 18:53 UTC
**Is your feature request related to a problem? Please describe.**
If I were to user OpenIdConnect middleware, there is an option to ".GetClaimsFromUserInfoEndpoint" which if set to "true" will automatically hit the userinfo endpoint from the discovery document and retrieve additional claims (whcih can be added to the ticket).

It appears that when using .AddMicrosoftIdentityWebApp there is no default option to enable this.  Even if I configure .AddMicrosoftGraph(<confighere>), the middleware WILL retrieve an access_token with the correct User.ReadBasic.All scope, but it will not use that to call the userinfo endpoint.... Do I have to manually configure an event?  

**Describe the solution you'd like**
I would like to see an option similar to "GetClaimsFromUserInfoEndpoint", to have those additional claims automatically added to the current set of User-Claims.

**Describe alternatives you've considered**
Abandoning .AddMicrosoftIdentityWebApp and using .AddOpenIdConnect instead, because this option gives everything I need and allows me to easily (and automatically) hit the userinfo endpoint.  The obvious down-side to this is that if our app also wants to use MicrosoftGraph API's for other reasons, there is additional config there.

**Comment by jmprieur** [comment] 2021-01-14 19:43
@m-hicks-OH 
Microsoft.Identity.Web already requests the claims from the user info endpoint in web apps. See https://github.com/AzureAD/microsoft-identity-web/blob/5539157a9e42c57d1a27b1be980caef6f8443086/src/Microsoft.Identity.Web/WebAppExtensions/MicrosoftIdentityWebAppAuthenticationBuilderExtensions.cs#L337

It's just that the claims you are looking fore are in the **IDToken**, not the access token.

cc: @jennyf19 (as this is an even easier solution than what we do today)

**Comment by m-hicks-OH** [comment] 2021-01-14 19:48
@jmprieur But it's not, I mean I'm looking at the back-channel HTTP request traffic and it's never making that call.  Additionally, when I check the User.Claims, those extra claims aren't there.

**Comment by m-hicks-OH** [comment] 2021-01-14 21:18
Perhaps I'm either not explaining myself or I'm doing something wrong, but how am I supposed to turn the GetClaimsFromUserInfoEndpoint option to true, when it's default, and it seems that the option is being ignored by the ConfigSection.  I looked through the constructor and service registration code you linked, and I see the part where it gets the GetClaimsFromUserInfoEndpoint value from the passed in MicrosoftIdentityOptions value, but It's still not hitting the userInfo endpoint even if I manually set that to true in the options action delagate for .AddMicrosoftIdentityWeb.

**Comment by jennyf19** [comment] 2021-01-15 17:18
similar [issue](https://github.com/AzureAD/microsoft-identity-web/issues/880)

**Comment by jmprieur** [comment] 2021-02-01 09:43
Closing as a duplicate of https://github.com/AzureAD/microsoft-identity-web/issues/880

**Closed by jmprieur** 2021-02-01 09:43 UTC
Labels: answered, enhancement, fundamentals, question
