### ISSUE TITLE
Cancel button redirects to /

### ISSUE THREAD

**Issue by hankovich** [AzureAD/microsoft-identity-web#620] opened 2020-09-29 11:19 UTC
On the B2C login form we have two additional links:
![image](https://user-images.githubusercontent.com/22914850/94551417-ffb1f980-025d-11eb-9c39-597b31f08df8.png)

which lead us to the next sections:
![image](https://user-images.githubusercontent.com/22914850/94551456-0e98ac00-025e-11eb-8c37-c5c4fe075d61.png)
![image](https://user-images.githubusercontent.com/22914850/94551480-16585080-025e-11eb-83bb-82ab736445da.png)

Both of them have `cancel` button in place.

But when I click `cancel` I'm redirected not to the main login form, but to `my_app_host/`.

Could you please describe how can I override this behavior and make those buttons redirect me to the login form (first image)?

**Comment by pmaytak** [comment] 2020-10-01 23:06
We have this [web app B2C](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/4-WebApp-your-API/4-2-B2C) sample. When I run it, the cancel button redirects to the login page correctly. Perhaps [Reply URL](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/4-WebApp-your-API/4-2-B2C#step-4-create-your-own-web-app) needs to be set?

**Comment by hankovich** [comment] 2020-10-05 13:27
Hi @pmaytak the problem was that in my application I have `[Authorize]` applied on a single action only when in the app you mentioned [it's applied globally](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/master/4-WebApp-your-API/4-2-B2C/Client/Startup.cs#L56). It also has `/` route (which leads to /Home/Index) and that makes cancel button work.

Ok, probably I know another case.

1. Open the app and go to https://localhost:5000/todolist/create
2. Log in properly
3. You are on `/todolist/create` as expected

But

1. Open the app and go to https://localhost:5000/todolist/create
2. Press `Forgot your password?`
3. Press `Cancel`
4. Log in properly
5. Boom! You are on `/`, but not on `/todolist/create` as requested

**Comment by pmaytak** [comment] 2020-10-07 00:19
Thank you for that detailed repro. We'll investigate.

**Comment by jennyf19** [comment] 2020-10-16 16:46
@pmaytak do you have an update on this?

**Comment by pmaytak** [comment] 2020-10-20 17:39
@jennyf19 I didn't get a chance to look at it. Could you investigate, if not I can make time after my current work item.

**Comment by pmaytak** [comment] 2020-10-24 06:28
@hankovich Apologies for a late reply. 

This behavior applies also to the Sign up, and Edit Profile flows. When a user cancels that action, the error is caught and redirected back to home page here:
https://github.com/AzureAD/microsoft-identity-web/blob/66103b7790904221f04f70592c8e6d4dcc73428c/src/Microsoft.Identity.Web/AzureADB2COpenIDConnectEventHandlers.cs#L83

And additionally in Microsoft.Identity.Web.UI `AccountController`, there are home page redirects after those user flows are successfully finished. Like here:
https://github.com/AzureAD/microsoft-identity-web/blob/66103b7790904221f04f70592c8e6d4dcc73428c/src/Microsoft.Identity.Web.UI/Areas/MicrosoftIdentity/Controllers/AccountController.cs#L144

I'll research a bit more on the fix.

**Comment by jmprieur** [comment] 2020-10-31 10:54
@hankovich the problem is that currently the "reset-password" flow is handled by the application. the b2C team is working on making it handled by the service itself (which should have been). When that's done, the behavior will be right.

Meanwhile, if you want to override the onRedirectToIdentityProvider even to detect that there is a password reset and it got cancelled, you might be able to do something. Would that work for you?
cc; @pmaytak

**Comment by hankovich** [comment] 2020-11-05 12:32
@jmprieur For now I do not want to handle it myself, I was thinking about it as a workaround for the issue with redirect.

Do you have any information on when the b2c team is going to release the changes you mentioned?

**Comment by jmprieur** [comment] 2020-11-05 13:05
@nickgmicrosoft  would you know?

**Comment by jennyf19** [comment] 2020-12-05 02:30
@hankovich we have been told end of Dec 2020, so we will see. We'll keep you posted.

**Comment by jennyf19** [comment] 2021-05-25 20:45
@nickgmicrosoft any update on this? 

closing as b2c issue.

**Closed by jennyf19** 2021-05-25 20:45 UTC
Labels: Answered, b2c, external, question

**Comment by nickgmicrosoft** [comment] 2021-05-28 22:48
Hi folks, 

This is not available. See [this](https://docs.microsoft.com/en-us/azure/active-directory-b2c/add-password-reset-policy?pivots=b2c-user-flow#self-service-password-reset-recommended) documentation to learn how to enable password reset within a sign/sign-up user flow so that your application doesn't need to deal with the redirect.

**Comment by aalokaswal** [comment] 2022-12-04 06:57
How cancel will be handled from custom policy for reset password. below I am using sub journeys for forget password.
<TrustFrameworkPolicy 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
xmlns="http://schemas.microsoft.com/online/cpim/schemas/2013/06"
 PolicySchemaVersion="0.3.0.0" 
 TenantId="xagrouptest.onmicrosoft.com" 
 PolicyId="B2C_1A_signinpolicy" 
 PublicPolicyUri="http://xagrouptest.onmicrosoft.com/B2C_1A_signinpolicy" >
  <BasePolicy>
    <TenantId>xagrouptest.onmicrosoft.com</TenantId>
    <PolicyId>B2C_1A_TrustFrameworkExtensions</PolicyId>
  </BasePolicy>

  <BuildingBlocks>

      
      

      
      

    <ClaimsSchema> 
    <ClaimType Id="isForgotPassword">
      <DisplayName>isForgotPassword</DisplayName>
      <DataType>boolean</DataType>
      <AdminHelpText>Whether the user has selected Forgot your Password</AdminHelpText>
    </ClaimType>

    <ClaimType Id="responseMsg">
    <DisplayName>Information</DisplayName>
    <DataType>string</DataType>
    <AdminHelpText>A claim responsible for holding response messages to send to the relying party</AdminHelpText>
    <UserHelpText>A claim responsible for holding response messages to send to the relying party</UserHelpText>
    <UserInputType>Paragraph</UserInputType>
    </ClaimType>

    
      <ClaimType Id="newPassword">
      <DisplayName>Password</DisplayName>
        <DataType>string</DataType>
        <AdminHelpText>Enter password</AdminHelpText>
        <UserHelpText>Enter password</UserHelpText>
        <UserInputType>Password</UserInputType>
      <PredicateValidationReference Id="StrongPassword" />
      </ClaimType>

    <ClaimType Id="reenterPassword">
        <DisplayName>Re enter password</DisplayName>
        <DataType>string</DataType>
        <AdminHelpText>Re Enter password</AdminHelpText>
        <UserHelpText>Re Enter password</UserHelpText>
      <PredicateValidationReference Id="StrongPassword" />
    </ClaimType>

  </ClaimsSchema>

  <Predicates>

  <Predicate Id="DisallowedWhitespace" Method="MatchesRegex">
        <UserHelpText>The password must not begin or end with a whitespace character.</UserHelpText>
        <Parameters>
          <Parameter Id="RegularExpression">(^\S.*\S$)|(^\S+$)|(^$)</Parameter>
        </Parameters>
      </Predicate>

  <Predicate Id="AllowedAADCharacters" Method="MatchesRegex">
    <UserHelpText>An invalid character was provided.</UserHelpText>
    <Parameters>
      <Parameter Id="RegularExpression">(^([0-9A-Za-zd@#$%^&amp;*-_+=[]{}|:',?/`~"();! ]|(.(?!@)))+$)|(^$)</Parameter>
    </Parameters>
  </Predicate>

      <Predicate Id="IsLengthBetween8And64" Method="IsLengthRange">
        <UserHelpText>The password must be between 8 and 64 characters.</UserHelpText>
        <Parameters>
          <Parameter Id="Minimum">8</Parameter>
          <Parameter Id="Maximum">64</Parameter>
        </Parameters>
      </Predicate>

      <Predicate Id="Lowercase" Method="IncludesCharacters">
        <UserHelpText>a lowercase letter</UserHelpText>
        <Parameters>
          <Parameter Id="CharacterSet">a-z</Parameter>
        </Parameters>
      </Predicate>

      <Predicate Id="Uppercase" Method="IncludesCharacters">
        <UserHelpText>an uppercase letter</UserHelpText>
        <Parameters>
          <Parameter Id="CharacterSet">A-Z</Parameter>
        </Parameters>
      </Predicate>

      <Predicate Id="Number" Method="IncludesCharacters">
        <UserHelpText>a digit</UserHelpText>
        <Parameters>
          <Parameter Id="CharacterSet">0-9</Parameter>
        </Parameters>
      </Predicate>

      <Predicate Id="Symbol" Method="IncludesCharacters">
        <UserHelpText>a symbol</UserHelpText>
        <Parameters>
          <Parameter Id="CharacterSet">@#$%^&amp;*\-_+=[]{}|\\:',.?/`~"();!</Parameter>
        </Parameters>
      </Predicate>

  </Predicates>

   <PredicateValidations>
      
      <PredicateValidation Id="StrongPassword">
        <PredicateGroups>
          <PredicateGroup Id="DisallowedWhitespaceGroup">
            <PredicateReferences>
              <PredicateReference Id="DisallowedWhitespace" />
            </PredicateReferences>
          </PredicateGroup>
          
          <PredicateGroup Id="LengthGroup">
            <PredicateReferences>
              <PredicateReference Id="IsLengthBetween8And64" />
            </PredicateReferences>
          </PredicateGroup>
          <PredicateGroup Id="CharacterClasses">
            <UserHelpText>The password must have at least 3 of the following:</UserHelpText>
            <PredicateReferences MatchAtLeast="3">
              <PredicateReference Id="Lowercase" />
              <PredicateReference Id="Uppercase" />
              <PredicateReference Id="Number" />
              <PredicateReference Id="Symbol" />
            </PredicateReferences>
          </PredicateGroup>
        </PredicateGroups>
      </PredicateValidation>
    </PredicateValidations>

  </BuildingBlocks>

  <ClaimsProviders>

<ClaimsProvider>
    <DisplayName>Azure Active Directory</DisplayName>
    <TechnicalProfiles>
      <TechnicalProfile Id="AAD-UserWriteUsingLogonEmail">
        <PersistedClaims>
          <PersistedClaim ClaimTypeReferenceId="passwordPolicies" DefaultValue="DisablePasswordExpiration, DisableStrongPassword"/>
        </PersistedClaims>
      </TechnicalProfile>
      <TechnicalProfile Id="AAD-UserWritePasswordUsingObjectId">
        <PersistedClaims>
          <PersistedClaim ClaimTypeReferenceId="passwordPolicies" DefaultValue="DisablePasswordExpiration, DisableStrongPassword"/>
        </PersistedClaims>
      </TechnicalProfile>
    </TechnicalProfiles>
  </ClaimsProvider>

    <ClaimsProvider>
    <DisplayName>Email Discovery</DisplayName>
    <TechnicalProfiles>
        <TechnicalProfile Id="LocalAccountDiscoveryUsingEmailAddress">
          <DisplayName>Reset password using email address</DisplayName>
          <Protocol Name="Proprietary" Handler="Web.TPEngine.Providers.SelfAssertedAttributeProvider, Web.TPEngine, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" />
          <Metadata>
            <Item Key="IpAddressClaimReferenceId">IpAddress</Item>
            <Item Key="ContentDefinitionReferenceId">api.localaccountpasswordreset</Item>
          </Metadata>
          <CryptographicKeys>
            
            
            <Key Id="client_secret" StorageReferenceId="B2C_1A_IdTokenHintKey" />
          </CryptographicKeys>
          <IncludeInSso>false</IncludeInSso>
          <OutputClaims>
            <OutputClaim ClaimTypeReferenceId="email" PartnerClaimType="Verified.Email" Required="true" />
            <OutputClaim ClaimTypeReferenceId="objectId" />
            <OutputClaim ClaimTypeReferenceId="userPrincipalName" />
            <OutputClaim ClaimTypeReferenceId="authenticationSource" />
          </OutputClaims>
          <ValidationTechnicalProfiles>
            <ValidationTechnicalProfile ReferenceId="AAD-UserReadUsingEmailAddress" />
          </ValidationTechnicalProfiles>
        </TechnicalProfile>
    </TechnicalProfiles>
    </ClaimsProvider>

    <ClaimsProvider>
    <DisplayName>Local Account</DisplayName>
    <TechnicalProfiles>
      <TechnicalProfile Id="ForgotPassword">
        <DisplayName>Forgot your password?</DisplayName>
        <Protocol Name="Proprietary" Handler="Web.TPEngine.Providers.ClaimsTransformationProtocolProvider, Web.TPEngine, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null"/>
        <OutputClaims>
          <OutputClaim ClaimTypeReferenceId="isForgotPassword" DefaultValue="true" AlwaysUseDefaultValue="true"/>
        </OutputClaims>
        <UseTechnicalProfileForSessionManagement ReferenceId="SM-Noop" /> 
      </TechnicalProfile>
      <TechnicalProfile Id="SelfAsserted-LocalAccountSignin-Email">
        <Metadata>
          <Item Key="setting.forgotPasswordLinkOverride">ForgotPasswordExchange</Item>
          <Item Key="setting.showSignupLink">false</Item>
           <Item Key="setting.showCancelButton">false</Item>
        </Metadata>
      </TechnicalProfile>
      <TechnicalProfile Id="LocalAccountWritePasswordUsingObjectId">
         <Metadata>
           <Item Key="setting.showCancelButton">false</Item>
        </Metadata>
        <UseTechnicalProfileForSessionManagement ReferenceId="SM-AAD" />
        
      </TechnicalProfile>
    </TechnicalProfiles>
  </ClaimsProvider>

     <ClaimsProvider>
      <DisplayName>My ID Token Hint ClaimsProvider</DisplayName>
      <TechnicalProfiles>
        <TechnicalProfile Id="IdTokenHint_ExtractClaims">
          <DisplayName> My ID Token Hint TechnicalProfile</DisplayName>
          <Protocol Name="None" />
          <Metadata>
            
            <Item Key="METADATA">https://xagrouptest.b2clogin.com/xagrouptest.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=B2C_1A_signinpolicy</Item>
            
            
            <Item Key="IdTokenAudience">1bdf2d2f-6b05-4633-89ab-6a2a7881a923</Item>
            <Item Key="issuer">https://localhost</Item>
          </Metadata>
          <CryptographicKeys>
            <Key Id="client_secret" StorageReferenceId="B2C_1A_IdTokenHintKey" />
          </CryptographicKeys>
          <OutputClaims>
            
            <OutputClaim ClaimTypeReferenceId="email" />
            <OutputClaim ClaimTypeReferenceId="displayName" />
            <OutputClaim ClaimTypeReferenceId="givenName" />
            <OutputClaim ClaimTypeReferenceId="surName" />
            <OutputClaim ClaimTypeReferenceId="objectId" />
          </OutputClaims>
        </TechnicalProfile>
      </TechnicalProfiles>
    </ClaimsProvider>
  </ClaimsProviders>

  <UserJourneys>
    <UserJourney Id="CustomSignIn">
      <OrchestrationSteps>

              <OrchestrationStep Order="1" Type="CombinedSignInAndSignUp" ContentDefinitionReferenceId="api.signuporsignin">
              <ClaimsProviderSelections>
                <ClaimsProviderSelection ValidationClaimsExchangeId="LocalAccountSigninEmailExchange" />
                <ClaimsProviderSelection TargetClaimsExchangeId="ForgotPasswordExchange" />
              </ClaimsProviderSelections>
              <ClaimsExchanges>
                <ClaimsExchange Id="LocalAccountSigninEmailExchange" TechnicalProfileReferenceId="SelfAsserted-LocalAccountSignin-Email" />
              </ClaimsExchanges>
            </OrchestrationStep>

            <OrchestrationStep Order="2" Type="ClaimsExchange">
              <Preconditions>
                <Precondition Type="ClaimsExist" ExecuteActionsIf="true">
                  <Value>objectId</Value>
                  
                  <Action>SkipThisOrchestrationStep</Action>
                </Precondition>
              </Preconditions>
              <ClaimsExchanges>
                <ClaimsExchange Id="ForgotPasswordExchange" TechnicalProfileReferenceId="ForgotPassword" />
              </ClaimsExchanges>
            </OrchestrationStep>

            <OrchestrationStep Order="3" Type="InvokeSubJourney">
            <Preconditions>
             <Precondition Type="ClaimsExist" ExecuteActionsIf="false">
             <Value>isForgotPassword</Value>
              <Action>SkipThisOrchestrationStep</Action>
               </Precondition>
             </Preconditions>
             <JourneyList>
              <Candidate SubJourneyReferenceId="PasswordReset" />
            </JourneyList>
            </OrchestrationStep>

            <OrchestrationStep Order="4" Type="ClaimsExchange" ContentDefinitionReferenceId="api.signuporsignin">
             <Preconditions>
             <Precondition Type="ClaimsExist" ExecuteActionsIf="false">
             <Value>isForgotPassword</Value>
              <Action>SkipThisOrchestrationStep</Action>
               </Precondition>
             </Preconditions>
             <ClaimsProviderSelections>
                <ClaimsProviderSelection ValidationClaimsExchangeId="LocalAccountSigninEmailExchangeAfterPwdReset" />
              </ClaimsProviderSelections>
              <ClaimsExchanges>
                <ClaimsExchange Id="LocalAccountSigninEmailExchangeAfterPwdReset" TechnicalProfileReferenceId="SelfAsserted-LocalAccountSignin-Email" />
              </ClaimsExchanges>
            </OrchestrationStep>

        <OrchestrationStep Order="5" Type="SendClaims" CpimIssuerTechnicalProfileReferenceId="JwtIssuer" />
      </OrchestrationSteps>
      <ClientDefinition ReferenceId="DefaultWeb" />
</UserJourney>
</UserJourneys>

<SubJourneys>
  <SubJourney Id="PasswordReset" Type="Call">
      <OrchestrationSteps>
        <OrchestrationStep Order="1" Type="ClaimsExchange">
          <ClaimsExchanges>
            <ClaimsExchange Id="PasswordResetUsingEmailAddressExchange" TechnicalProfileReferenceId="LocalAccountDiscoveryUsingEmailAddress" />
          </ClaimsExchanges>
        </OrchestrationStep>
        <OrchestrationStep Order="2" Type="ClaimsExchange">
          <ClaimsExchanges>
            <ClaimsExchange Id="NewCredentials" TechnicalProfileReferenceId="LocalAccountWritePasswordUsingObjectId" />
          </ClaimsExchanges>
        </OrchestrationStep>

         
        

      </OrchestrationSteps>
    </SubJourney>

    <SubJourney Id="RedirectToSignIn" Type="Call">
      <OrchestrationSteps>
        
        <OrchestrationStep Order="1" Type="ClaimsExchange" ContentDefinitionReferenceId="api.signuporsignin">
          <ClaimsProviderSelections>
                <ClaimsProviderSelection ValidationClaimsExchangeId="LocalAccountSigninEmailExchange" />
                <ClaimsProviderSelection TargetClaimsExchangeId="ForgotPasswordExchange" />
              </ClaimsProviderSelections>
          <ClaimsExchanges>
            <ClaimsExchange Id="SelfAsserted-LocalAccountSignin-Email" TechnicalProfileReferenceId="SelfAsserted-LocalAccountSignin-Email" />
          </ClaimsExchanges>
        </OrchestrationStep>
      </OrchestrationSteps>
    </SubJourney>

</SubJourneys>

  <RelyingParty>
    <DefaultUserJourney ReferenceId="CustomSignIn" />
    <TechnicalProfile Id="PolicyProfile">
      <DisplayName>PolicyProfile</DisplayName>
      <Protocol Name="OpenIdConnect" />
      <OutputClaims>
        <OutputClaim ClaimTypeReferenceId="displayName" />
        <OutputClaim ClaimTypeReferenceId="givenName" />
        <OutputClaim ClaimTypeReferenceId="surname" />
        
        
        <OutputClaim ClaimTypeReferenceId="signInNames.emailAddress" PartnerClaimType="email" />
        <OutputClaim ClaimTypeReferenceId="tenantId" AlwaysUseDefaultValue="true" DefaultValue="{Policy:TenantObjectId}" />
        <OutputClaim ClaimTypeReferenceId="objectId" PartnerClaimType="sub" />
        <OutputClaim ClaimTypeReferenceId="isForgotPassword" DefaultValue="false" />
      </OutputClaims>
      <SubjectNamingInfo ClaimType="sub" />
    </TechnicalProfile>
  </RelyingParty>
</TrustFrameworkPolicy>

**Comment by RoshmiAugustine** [comment] 2023-04-11 08:06
any update on this?

**Comment by jannef** [comment] 2023-10-04 10:53
> any update on this issue? How cancel will be handled from the custom policy for reset password?

Here is the documentation:
https://learn.microsoft.com/en-us/azure/active-directory-b2c/self-asserted-technical-profile#metadata

Such functionality has not been added and it's been 3 years. I thinks it's time to accept this is never going to happen.

**Comment by jmprieur** [comment] 2023-10-05 01:55
@jannef : is the problem in Microsoft.Identity.Web? or in the B2C service?

**Comment by andreyks95** [comment] 2026-01-06 08:46
One way to handle a redirect when clicking the Cancel button on the Sign Up form in Azure B2C is the following:

**1. Make sure that JavaScript execution is enabled on the page**

Ensure that JavaScript execution is allowed on the page according to the article: [Enable JavaScript and page layout versions in Azure Active Directory B2C](https://learn.microsoft.com/en-us/azure/active-directory-b2c/javascript-and-page-layout?pivots=b2c-custom-policy)


In my case, I used a Custom Policy in the _Identity Experience Framework_.
For _SignUpOrSignin.xml_, I added _ScriptExecution_:

```
<RelyingParty>
<DefaultUserJourney ReferenceId="SignUpOrSignIn" />
  <UserJourneyBehaviors>
    <ScriptExecution>Allow</ScriptExecution>
  </UserJourneyBehaviors>
  ...
</RelyingParty>
```


**2. Add a script reference to the custom page**

For the custom page, a script reference was added before the closing </head> tag:

`<script src="https://yourdomain.com/cancel-handler.js" defer></script>`

To add your custom page in TRUSTFRAMEWORKEXTENSIONS.xml, locate the BuildingBlocks section and insert the following block:

```
<ContentDefinitions>
  <ContentDefinition Id="api.signuporsignin">
    <LoadUri>https://yourdomain.com/customsignup.html</LoadUri>
    <RecoveryUri>~/common/default_page_error.html</RecoveryUri>
    <DataUri>urn:com:microsoft:aad:b2c:elements:contract:unifiedssp:2.1.2</DataUri>
    <Metadata>
      <Item Key="DisplayName">Signin and Signup</Item>
    </Metadata>
  </ContentDefinition>
</ContentDefinitions>
```
**3. Attach a Cancel button event handler**

Attach an event handler to the Cancel button and perform a redirect to the page you need.

If you have any questions, please feel free to reach out to me.
