### ISSUE TITLE
Why does the extension method 'MicrosoftGraphAppOnly' setup a Scoped registration for GraphServiceClient instead of IGraphServiceClient?

### ISSUE THREAD

**Issue by StefH** [AzureAD/microsoft-identity-web#886] opened 2021-01-17 11:35 UTC
In this code:
https://github.com/AzureAD/microsoft-identity-web/blob/master/src/Microsoft.Identity.Web.MicrosoftGraph/MicrosoftGraphExtensions.cs#L142

The `GraphServiceClient` is registered as `GraphServiceClient`.

But why is not the **interface** registered ?
Like:
``` c#
builder.Services.AddScoped<IGraphServiceClient, GraphServiceClient>(serviceProvider => // ...
```

Registering as an interface makes it possible to use the IGraphServiceClient in your own implementation classes like:

``` c#
public MyClient(IGraphServiceClient graphServiceClient)
{
    _graphServiceClient = graphServiceClient;
}
```
And mocking the interface in unit testing is also possible in this way.

**Comment by jmprieur** [comment] 2021-01-17 20:14
Closing as "by design" as duplicates of 
- https://github.com/AzureAD/microsoft-identity-web/issues/860
- https://github.com/AzureAD/microsoft-identity-web/issues/625

Please @StefH, see the justification (coming from the Graph SDK team) in these issues

**Closed by jmprieur** 2021-01-17 20:14 UTC
Labels: by design, duplicate
