### ISSUE TITLE
[Bug] Microsoft Identity Platform doesn't work as an external login with Identity Framework

### ISSUE THREAD

**Issue by Blackleones** [AzureAD/microsoft-identity-web#260] opened 2020-06-26 13:48 UTC
**Which Version of Microsoft Identity Web are you using ?**
Note that to get help, you need to run the latest version. 

**Where is the issue?**
* Web App
    * [x] Sign-in users
    * [ ] Sign-in users and call web APIs
* Web API
    * [ ] Protected web APIs (Validating tokens)
    * [ ] Protected web APIs (Validating scopes)
    * [ ] Protected web APIs call downstream web APIs
* Token cache serialization
     * [ ] In Memory caches
     * [ ] Session caches
     * [ ] Distributed caches

Other? - please describe;

**Is this a new or existing app?**
This app started from your [sample code ](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/1-WebApp-OIDC/1-1-MyOrg) 

**Repro**

I've created a sample project so you can try it by yourself. What you have to do is:

1. open the solution
2. fill domain, tenant, and client id inside appsettings.json
3. run update-database command
4. run the website
5. click on "openIdConnect" button and login using your Microsoft account.
6. you will get the error

My sample code: [MicrosoftIdentityPlatformWithIdentityFramework.zip](https://github.com/AzureAD/microsoft-identity-web/files/4837268/MicrosoftIdentityPlatformWithIdentityFramework.zip)

**Expected behavior**
 - Typical external login Identity Framework behavior

**Actual behavior**
- After filling my user credentials on Azure AD portal, I get the following error: **Error loading external login information.**

**Comment by jmprieur** [comment] 2020-06-26 13:52
Thanks for raising, and providing a repro, @Blackleones 
I think it's a duplicate of https://github.com/AzureAD/microsoft-identity-web/issues/133
It's not yet supported.

**Comment by Blackleones** [comment] 2020-06-26 16:06
Thank you @jmprieur. 
I would like to suggest you create some sample codes using Blazor (server-side and client-side). Should I open a new issue for this?

**Comment by jmprieur** [comment] 2020-06-26 18:44
It's on the backlog, but not highest priority, @Blackleones : https://github.com/AzureAD/microsoft-identity-web/milestone/15
Contributions are welcome, BTW :)

cc: @kalyankrishna1 @TiagoBrenck @Shama-K @jennyf19 @pmaytak

**Comment by jennyf19** [comment] 2021-05-25 20:39
@Blackleones I believe this is fixed, do you mind trying with the latest version (1.11)? Thank you.

**Comment by jennyf19** [comment] 2021-05-25 20:39
closing, but reopen if necessary.

**Closed by jennyf19** 2021-05-25 20:39 UTC
Labels: duplicate, enhancement
