### ISSUE TITLE
Browser blocks Web site secured by Azure AD

### ISSUE THREAD

**Issue by WenningQiu** [AzureAD/microsoft-identity-web#2110] opened 2023-03-13 15:07 UTC
I don't believe the issue is related to Microsoft.Identity.Web package but I am trying to seek help from the community.

I have a web site secured by Azure AD which has recently become broken.

When a user logs in, the interaction with AAD works fine but at the last step the browser would decide to block the web site URL with the message below. The URL remains blocked until cookies and site data are cleared.
![image](https://user-images.githubusercontent.com/4291622/224740666-23b6b2bf-5769-400d-b9e1-d0b9c4f9def6.png)

The behavior is not universal but may be related to certain hosts - it works fine when I host the web site on my laptop (Windows 10 Enterprise), but has the problem when hosted on the dev VM (Windows Server 2016).

I suspect it might be cert related, but am confused about the following:

- the fact that the browser accepts the URL in the first message but later (after AAD interaction) decides to consider that the website no longer trusted.
- the fact that it has the described behavior on one registered app, but works with no issue on another registered app in the same tenant.

The screenshots and message trace are captured with Firefox, but other browsers have the same behavior.

Below is the screenshot of the login message traces. I have attached that HAR trace.
![image](https://user-images.githubusercontent.com/4291622/224740742-d84d0780-5bfa-44a0-a196-8b1b9048d91f.png)
[MessageTrace.Har.gz](https://github.com/AzureAD/microsoft-identity-web/files/10958674/MessageTrace.Har.gz)

**Comment by WenningQiu** [comment] 2023-03-13 15:36
After comparing the working app and broken app, several differences were found. The reported issue went away after I removed the token configuration below from the broken app. I am still clueless about the correlation of the token configuration and the issue.

![image](https://user-images.githubusercontent.com/4291622/224750674-2cb6fce4-e299-47c2-97b8-15f7b0be6845.png)

**Comment by jmprieur** [comment] 2023-03-17 04:01
The groups claim can become very big, and maybe bigger than the size limit for a cookie?

**Comment by jmprieur** [comment] 2023-03-17 04:01
Closing as you seem to have found the root cause, and it's not a Microsoft.Identity.Web issue
feel free to reopen if you disagree.

**Closed by jmprieur** 2023-03-17 04:01 UTC
Labels: question, Answered
