### ISSUE TITLE
AddProtectedWebAPI loads secrets from an unsecured appsettings.json file

### ISSUE THREAD

**Issue by nschuessler** [AzureAD/microsoft-identity-web#323] opened 2020-07-15 19:30 UTC
Following the instructions from the 4-1-MyOrg sample in the sample [repository](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2.git), it puts the configuration/secrets in the `appsettings.json` file which seems to run counter to best security practices.

How do I achieve this configuration step in the tutorial with secrets manually pulled from a keyvault?

```
 services.AddProtectedWebApi(Configuration)
       .AddInMemoryTokenCaches();
```

Thanks

**Comment by jmprieur** [comment] 2020-07-15 20:20
hi @nschuessler 
The appsettings.json is usually on a server which cannot be accessed so this is not necessarilly unsecure
However, you are right that best practices are to access a certificate from KeyVault.

This article explains how to do it:
https://github.com/AzureAD/microsoft-identity-web/wiki/Using-certificates

**Comment by nschuessler** [comment] 2020-07-15 21:00
```
   "Instance": "https://login.microsoftonline.com/",
    "Domain": "msidentitysamplestesting.onmicrosoft.com",
    "TenantId": "7f58f645-c190-4ce5-9de4-e2b7acd2a6ab",
    "ClientId": "86699d80-dd21-476a-bcd1-7c1a3d471f75",
```

I'm not using certificates though. I'm just reading these four values from secrets from the valut.
How do I set them with the add protected web api?

Do I add them into `Configuration` or is there another way with the 
```
options => {
    // set something here
}
```

**Comment by jmprieur** [comment] 2020-07-16 04:39
@nschuessler. Yes. With Microsoft.Identity.Web 0.2.0-preview, you could write something like that (or the equivalent with the information you got from KeyVault):

```CSharp
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
                    .AddMicrosoftWebApp(MicrosoftIdentityOptions =>
                    {
                        MicrosoftIdentityOptions.Instance = "https://login.microsoftonline.com/";
                        MicrosoftIdentityOptions.Domain = "msidentitysamplestesting.onmicrosoft.com";
                        MicrosoftIdentityOptions.TenantId = "7f58f645-c190-4ce5-9de4-e2b7acd2a6ab";
                        MicrosoftIdentityOptions.ClientId = "86699d80-dd21-476a-bcd1-7c1a3d471f75";
                    });
}
```

However, I'd like to understand your scenario better to see if we can improve your experience? 
- where is your web app / web api hosted? 
- It sounds complicated to read these values from Key Vault as none of them is a secret: the **ClientSecret** would be one when you web app calls a web API, but in confidential client applications, this should not be a problem.
- what security guidance are you refering to, that impose you to read these values from Key Vault.


To

**Comment by nschuessler** [comment] 2020-07-16 14:34
Thanks. I'm getting 401 unauthorized now. Gonna work on the client side to verify.

My web API is hosted in Azure.

I keep most of my config and secrets in the key vault so that it isn't spread around in various files and environment variables. I pre-load the values from the key vault so they appear in `Configuration`. It also makes it quite clear to ppl maintaining code that no secrets or config should ever be checked into the code branch because there is no file to add them to and accidentally commit.

I am using the Managed Service Identity for the service (Web API) and the development tools also used Managed Service Identity  when debugging so that specific users can access the config and secrets from the key vault.

The second benefit is that I can dynamically change the config in the key vault and just restart the app w/o having to redeploy.

Because of the clean startup / access to the vault the Managed Service Identity provides and the general guidance that key vault (or environment variables) should be used for secrets, it seems easier to have one way to store everything.

**Comment by jmprieur** [comment] 2020-07-30 18:24
Closing as duplicate of #269

**Closed by jmprieur** 2020-07-30 18:24 UTC
Labels: answered, enhancement, question
