### ISSUE TITLE
[Question] How to get OBO token from an event handler

### ISSUE THREAD

**Issue by hrazmsft** [AzureAD/microsoft-identity-web#441] opened 2020-08-12 23:31 UTC
How can I get an OBO access token in an event handler like:

```
[HttpPost]
public IActionResult ProcessData(string data)
{
    var processor = new Processor();

    processor.Finished += async (s, e) =>
    {
        var accessToken = await this
            ._tokenAcquisition
            .GetAccessTokenForUserAsync(new[] { "Files.ReadWrite" }, user: this.User);

        await WriteToOneDrive(accessToken, e.Data);
    };

    processor.processAsync(data); // Run async without awaiting

    return NoContent();
}
```

In this case the `this.User` is already disposed, and even without it, `GetAccessTokenForUserAsync` crashes with NullObjectException.

My process takes a very long time (hours).

How can I get the token inside a callback when I need it?

**Comment by jmprieur** [comment] 2020-08-13 08:28
@hraz-msft when your start your long running process, you should keep some claims about the user (at least the home tenant id and home object id), and then you can use `ClaimsPrincipalFactory.FromTenantIdAndObjectId` to get back a claims principal, and pass it instead of this.User.

https://github.com/AzureAD/microsoft-identity-web/blob/41195539af65836b464b063c186842896ab15e0e/src/Microsoft.Identity.Web/ClaimsPrincipalFactory.cs#L36


So I would try:

```CSharp
[HttpPost]
public IActionResult ProcessData(string data)
{
    var processor = new Processor();
    string oid = User.GetObjectId();
    string tid = User.GetTenantId();

    processor.Finished += async (s, e) =>
    {
        var accessToken = await this
            ._tokenAcquisition
            .GetAccessTokenForUserAsync(
              new[] { "Files.ReadWrite" }, 
              user: ClaimsPrincipalFactory.FromTenantIdAndObjectId(tid, oid));

        await WriteToOneDrive(accessToken, e.Data);
    };

    processor.processAsync(data); // Run async without awaiting

    return NoContent();
}
```

**Comment by hraz-msft** [comment] 2020-08-13 09:14
Hmm, it still crushing internally... The `tid` and `oid` are valid. 

![image](https://user-images.githubusercontent.com/66222191/90116437-28d60380-dd5e-11ea-80c2-ac692bb1fcdb.png)

**Comment by jmprieur** [comment] 2020-08-13 14:16
I think that the problem is that the HttpContext is null, or HttpContext.Items is null:

https://github.com/AzureAD/microsoft-identity-web/blob/41195539af65836b464b063c186842896ab15e0e/src/Microsoft.Identity.Web/HttpContextExtensions.cs#L30

**Comment by pmaytak** [comment] 2020-08-17 06:50
@hraz-msft, which version of Microsoft Identity Web do you use?

As of 0.2.2-preview, we added a null-conditional operator, so `GetTokenUsedToCallWebAPI` is not called on a null `HttpContext`.
https://github.com/AzureAD/microsoft-identity-web/blob/fe145b3fbe75960faead1476176f7c63b8afd976/src/Microsoft.Identity.Web/TokenAcquisition.cs#L277

If you are using the latest version, then most likely the `HttpContext.Items` is null, in which case, Jean-Marc's code suggestion should help.

**Comment by pmaytak** [comment] 2020-08-28 16:49
Hi @hraz-msft, is this still an issue for you?

**Comment by hraz-msft** [comment] 2020-08-28 18:13
Yes, it is still an issue that I don't know how to solve directly. I've found several workarounds like blocking the request until the operation done or sumbit a request to the sercer itself to simulate Webhook. But I don't have direct solution

**Comment by pmaytak** [comment] 2020-08-31 19:04
Can you verify that the issue still exists in version 0.2.2-preview or later?

**Comment by hraz-msft** [comment] 2020-08-31 19:11
Yes, in 0.2.3-preview there is no null pointer exception, but there is another exception.

![image](https://user-images.githubusercontent.com/66222191/91757390-e40ff080-ebd6-11ea-9ce6-1b83c404b5f9.png)

**Comment by jennyf19** [comment] 2020-08-31 20:45
@hraz-msft there is a bug in this method. I'll get a fix out today, and it will be in our next release.

**Comment by jennyf19** [comment] 2020-09-03 12:50
@hraz-msft do you want to try out the master branch and see if the initial issue is resolved?

**Comment by hraz-msft** [comment] 2020-09-03 13:27
Hi @jennyf19 I still can't get a token inside a callback with the latest master (error below).

I've open a repo with sample code with repro of the problem [here](https://github.com/hraz-msft/ms-identity-javascript-react-spa-dotnetcore-webapi-obo/blob/master/ProfileAPI/Controllers/ProfileController.cs#L49)

![image](https://user-images.githubusercontent.com/66222191/92120188-68de5280-ee01-11ea-8d82-358df8be1f97.png)

**Comment by jmprieur** [comment] 2020-10-08 18:28
@hraz-msft does it still repro with Microsoft.Identity.Web 1.1.0 ?

**Comment by hraz-msft** [comment] 2020-10-12 08:47
Hi @jmprieur, I don't have the code and the app registration anymore. You can use my repro code to test it, it will be faster.
https://github.com/hraz-msft/ms-identity-javascript-react-spa-dotnetcore-webapi-obo/blob/master/ProfileAPI/Controllers/ProfileController.cs#L49

**Closed** 2021-05-28 18:16 UTC
Labels: P2, needs documentation

**Comment by hrazmsft** [comment] 2021-05-28 19:00
@jmprieur thanks for the example! I just want to confirm. Instead of generating the token in the long action, you trigger a request, simulatiing a webhook, so a controller will generate the OBO token at the end...

Please correct me if I'm wrong, sending such webhook with the incoming user token may not work if the token is going to expire soon... If the token is going to be expired in less than 10 minutes of the timer, the second request in the timer will going to fail...

But nice workaround!

**Comment by jmprieur** [comment] 2021-05-28 19:06
@hrazmsft : this will actually work (soon when [this](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2623) bug is fixed in MSAL.NET) as the OBO token will be refreshed automatically even when it has expired (as MSAL.NET has the refresh token)

**Comment by hrazmsft** [comment] 2021-05-28 19:13
Maybe I'm missing something...

Here is what I meant:
![image](https://user-images.githubusercontent.com/66222191/120031506-90b1be00-c001-11eb-8b2d-3de0734ebb44.png)

If this token will be expired before the timer ticks, the request will send with an expired token. In this case, the request to `callback` will be rejected by ASP.

**Comment by jmprieur** [comment] 2021-05-28 19:24
Oh yes, sorry, @hrazmsft 
you'd better start your long running process from the Timer (with a timer (0))

**Comment by hrazmsft** [comment] 2021-05-28 20:03
@jmprieur how it will prevent the token from been expired?

**Comment by jmprieur** [comment] 2021-05-31 10:10
even if the incoming token expires, Microsoft.Identity.Web will get (using MSAL.NET):
- an OBO token (that will also expire), 
- but also a refresh token, which will enable your web API to get more OBO tokens for as long as 90 days

**Comment by hrazmsft** [comment] 2021-05-31 10:16
I don't understand how :). We have a server with this configuration:

![image](https://user-images.githubusercontent.com/66222191/120178351-1ad07100-c212-11eb-8c98-53391c8206ad.png)

In our client, we use `@azure/msal-react` to get a token. Each token expires after 1 hour.
If we send an expired token, the server rejects the request with 401...

So how sending expired tokens should work in your case?

**Comment by jmprieur** [comment] 2021-05-31 10:38
That won't work, @hrazmsft 
if the web API adds a callback to itself and reuses the incoming token as a key, it will work, but not if it's called from outside (like from your client)

**Comment by hrazmsft** [comment] 2021-05-31 11:14
Interesting! Didn't know that. How does it know if it is a callback from inside or outside?
