### ISSUE TITLE
[Bug] Name and emails claims missing after editing account

### ISSUE THREAD

**Issue by leaderanalytics** [AzureAD/microsoft-identity-web#322] opened 2020-07-15 17:35 UTC
**Which version of Microsoft Identity Web are you using?**
Note that to get help, you need to run the latest version. 

This behavior was observed using both 0.1.5-preview and 0.2.0-preview.

**Where is the issue?**
* Web app
    * [x ] Sign-in users
    * [ ] Sign-in users and call web APIs
* Web API
    * [ ] Protected web APIs (validating tokens)
    * [ ] Protected web APIs (validating scopes)
    * [ ] Protected web APIs call downstream web APIs
* Token cache serialization
     * [ ] In-memory caches
     * [ ] Session caches
     * [ ] Distributed caches
* Other (please describe)

**Is this a new or an existing app?**

**Repro**

[Clone this repo](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/1-WebApp-OIDC/1-5-B2C)
Sign in (this test was run using an Outlook account).
Note user name is displayed in nav bar.
Click claims. Note name and emails claims.
Click Edit Profile.  Do not make changes.
Click Continue.
Note name is missing in nav bar.
Click claims. name and emails claims are missing.

**Comment by jennyf19** [comment] 2020-07-16 15:12
@leaderanalytics I think the issue is we're using the current HttpContext and pulling the policy from there, which is edit profile, and the correct claims do not show up, as you want to go back to the su_si policy. We will investigate. thanks for letting us know.

**Comment by jennyf19** [comment] 2020-07-17 21:58
@leaderanalytics Can you try with the latest master branch? I believe this has been fixed. You will probably need to use the new API:

You'll need to do two things to try it out.
- First, in the [TodoListController](https://github.com/AzureAD/microsoft-identity-web/blob/jennyf/b2cPolicyLookup/tests/B2CWebAppCallsWebApi/Client/Controllers/TodoListController.cs#L25), add in the userFlow value you want to target in the `AuthorizeForScopes` attribute.

```csharp
[AuthorizeForScopes(ScopeKeySection = "TodoList:TodoListScope", UserFlow = "b2c_1_susi")]
```
- Second, specify the **same** userFlow value in [`PrepareAuthenticatedClient`](https://github.com/AzureAD/microsoft-identity-web/blob/jennyf/b2cPolicyLookup/tests/B2CWebAppCallsWebApi/Client/Services/TodoListService.cs#L127) in TodoListService.

```csharp
 private async Task PrepareAuthenticatedClient(string userFlow)
{
          // Each user flow is a separate authorization server. 
          // specify which user flow is connected to the web API.
          var accessToken = await _tokenAcquisition.GetAccessTokenForUserAsync(new[] { _TodoListScope, }, userFlow:userFlow);
          Debug.WriteLine($"access token-{accessToken}");
...
```

**Comment by jennyf19** [comment] 2020-08-01 01:23
@leaderanalytics closing as we need more info, but feel free to reopen if needed

**Closed by jennyf19** 2020-08-01 01:23 UTC
Labels: b2c, investigate, more info needed, question, web app
