### ISSUE TITLE
How to investigate IDX20803: Unable to obtain configuration from: 'System.String' ?

### ISSUE THREAD

**Issue by Servellia** [AzureAD/microsoft-identity-web#850] opened 2020-12-21 16:59 UTC
I have a .net core 3.1 Web app, that is connecting to AzureAD. I want to expose this application via a local Kubernetes cluster, where NGINX is used as a reverse proxy. In my configuration I am removing https from the application alltogether to get it to run on http first.

This approach work fine in the following scenarios:

- local debugging
- spinning up in Docker
- docker-compose

However, once I package the application and roll it out to K8s I get the following exception:

```
user@machine:~/$ curl 10.152.183.240/health
System.InvalidOperationException: IDX20803: Unable to obtain configuration from: 'System.String'.
 ---> System.IO.IOException: IDX20804: Unable to retrieve document from: 'System.String'.
 ---> System.Net.Http.HttpRequestException: Resource temporarily unavailable
 ---> System.Net.Sockets.SocketException (11): Resource temporarily unavailable
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(String address, CancellationToken cancel)
   --- End of inner exception stack trace ---
   at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(String address, CancellationToken cancel)
   at Microsoft.Identity.Web.InstanceDiscovery.IssuerConfigurationRetriever.GetConfigurationAsync(String address, IDocumentRetriever retriever, CancellationToken cancel)
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
   --- End of inner exception stack trace ---
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync()
   at Microsoft.Identity.Web.Resource.MicrosoftIdentityIssuerValidatorFactory.GetAadIssuerValidator(String aadAuthority)
   at Microsoft.Identity.Web.MicrosoftIdentityWebApiAuthenticationBuilderExtensions.<>c__DisplayClass3_0.<AddMicrosoftIdentityWebApiImplementation>b__0(JwtBearerOptions options, IServiceProvider serviceProvider, IOptionsMonitor`1 microsoftIdentityOptionsMonitor)
   at Microsoft.Extensions.Options.ConfigureNamedOptions`3.Configure(String name, TOptions options)
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.OptionsMonitor`1.<>c__DisplayClass11_0.<Get>b__0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Microsoft.Extensions.Options.OptionsCache`1.GetOrAdd(String name, Func`1 createOptions)
   at Microsoft.Extensions.Options.OptionsMonitor`1.Get(String name)
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.InitializeAsync(AuthenticationScheme scheme, HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationHandlerProvider.GetHandlerAsync(HttpContext context, String authenticationScheme)
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

HEADERS
=======
Accept: */*
Host: 10.152.183.240
User-Agent: curl/7.68.0
```

Looking at the callstack, I am assuming this has something to do with the configuration being passed in, but I cannot explain this to myself, since I've stuck them in the appsettings.json during development and do not touch them

Just to make it complete, here are the manifests, if this is of interest:

apiVersion: v1
kind: Service
metadata:
    name: xxx-api-svc
spec:
    type: LoadBalancer
    ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31112
      name: "http"
    selector:
        app: xxx-api
---
apiVersion : apps/v1
kind: Deployment
metadata:
  name: xxx-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xxx-api
  template:
    metadata:
      labels:
        app: xxx-api 
    spec:
      hostname: xxx-api-dev
      containers:
        - name: his-api 
          image: localhost:32000/xxx.api
          env:
          - name: "ASPNETCORE_ENVIRONMENT"
            value: "Development"
          - name: "ASPNETCORE_URLS"
            value: "http://+:80"
          ports:
          - containerPort: 80

**Comment by jmprieur** [comment] 2020-12-21 18:21
Closing as dupe of #851

**Closed by jmprieur** 2020-12-21 18:21 UTC
Labels: question
