### ISSUE TITLE
[Feature Request] Unable to mock the issuer metadata url.

### ISSUE THREAD

**Issue by v-michaelmi** [AzureAD/microsoft-identity-web#1745] opened 2022-06-01 18:41 UTC
**Is your feature request related to a problem? Please describe.**
I want to be able to run E2E tests in a local environment. When I try to use a spoofed OAuth2 server and configure an application to use this server the server creates errors by requesting metadata from Azure for an app that does not exist.

**Describe the solution you'd like**
I'd like to disable metadata discovery or customize the endpoint.

**Describe alternatives you've considered**
I could manually make requests to my spoofed local OAuth2 server but I want to make some shareable examples using more 'out of the box' methods such as `AddMicrosoftIdentityWebApp`

**Comment by jmprieur** [comment] 2022-07-15 02:11
@v-michaelmi : proposing to close this one as a duplicate of #1786 
Feel free to reopen if you disagree.

**Closed by jmprieur** 2022-07-15 02:11 UTC
Labels: enhancement, Feature Request
