### ISSUE TITLE
[Bug] MicrosoftGraphExtensions: GraphServiceClient is added to the DI container as the TImplementation, TImplementation, not TService, TImplementation

### ISSUE THREAD

**Issue by DOMZE** [AzureAD/microsoft-identity-web#1194] opened 2021-05-13 14:32 UTC
**Which version of Microsoft Identity Web are you using?**
Microsoft.Identity.Web 1.9.2
Microsoft.Identity.Web.MicrosoftGraph 1.9.2

**Where is the issue?**
* Other (please describe)
The GraphServiceClient is added to the DI as `<GraphServiceClient,GraphServiceClient>` as seen in https://github.com/AzureAD/microsoft-identity-web/blob/master/src/Microsoft.Identity.Web.MicrosoftGraph/MicrosoftGraphExtensions.cs

In our classes implementation, we can't use `IGraphServiceClient` in our constructor directly, but rather making us having to use the factory to create our classes such as:

```csharp
services.AddScoped<IClass, Class>(sp =>
{
	var client = sp.GetRequiredService<GraphServiceClient>();
	return new Class(client);
});
```
Using a hard dependency on `GraphServiceClient` renders our class hard to test.

**Is this a new or an existing app?**
This is a new app

**Expected behavior**
Having our class definition such as

```csharp
public Class(IGraphServiceClient graphServiceClient)
{
	...
}
```
and registered in the DI as:
```csharp
services.AddScoped<IClass, Class>();
```
should work as is.

**Actual behavior**
The DI container throws an exception saying that `IGraphServiceClient` is not registered.

**Possible solution**
Replace the DI registration in the extension file to `services.AddScope<IGraphServiceClient, GraphServiceClient>(...)` instead of  `services.AddScope<GraphServiceClient, GraphServiceClient>(...)`

**Comment by jmprieur** [comment] 2021-05-14 08:23
Duplicate of https://github.com/AzureAD/microsoft-identity-web/issues/860 and https://github.com/AzureAD/microsoft-identity-web/issues/625

@DOMZE, please see the [comment here](https://github.com/AzureAD/microsoft-identity-web/issues/625#issuecomment-702765953), this is against the recommendation from the Graph SDK team. Closing as by-design.
cc: @darrelmiller

**Closed by jmprieur** 2021-05-14 08:23 UTC
Labels: by design, enhancement
