### ISSUE TITLE
[Bug] Web service fails to start if AAD endpoint is unavailable: System.InvalidOperationException: IDX20803: Unable to obtain configuration

### ISSUE THREAD

**Issue by abatishchev** [AzureAD/microsoft-identity-web#1035] opened 2021-03-02 07:54 UTC
**Which version of Microsoft Identity Web are you using?**

Azure.Identity 1.4.0
Microsoft.AspNetCore.Authentication.AzureAD.UI 3.1.10

**Where is the issue?**
* Web app
    * [ ] Sign-in users
    * [ ] Sign-in users and call web APIs
* Web API
    * [x] Protected web APIs (validating tokens)
    * [x] Protected web APIs (validating scopes)
    * [ ] Protected web APIs call downstream web APIs
* Token cache serialization
     * [ ] In-memory caches
     * [ ] Session caches
     * [ ] Distributed caches
* Other (please describe)

**Repro**

Right now AAD PPE is down so when I attempt to start my ASP.NET Core 3.1 app, it fails with an exception:

```
System.InvalidOperationException: IDX20803: Unable to obtain configuration from: 'https://login.windows-ppe.net/common/discovery/instance?authorization_endpoint=https://login.windows-ppe.net/common/oauth2/v2.0/authorize&api-version=1.1'.
 ---> System.IO.IOException: IDX20807: Unable to retrieve document from: 'https://login.windows-ppe.net/common/discovery/instance?authorization_endpoint=https://login.windows-ppe.net/common/oauth2/v2.0/authorize&api-version=1.1'. HttpResponseMessage: 'StatusCode: 429, ReasonPhrase: 'Too Many Requests', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
{
  Retry-After: 20
  client-request-id: de92fb49-5113-4e67-b20c-d023f22811f6
  Set-Cookie: stsservicecookie=estsppe; path=/; secure; httponly
  Date: Tue, 02 Mar 2021 07:42:28 GMT
  Content-Length: 17
  Content-Type: text/HTML
}', HttpResponseMessage.Content: 'Too Many Requests'.
   at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(String address, CancellationToken cancel)
   at Microsoft.Identity.Web.InstanceDiscovery.IssuerConfigurationRetriever.GetConfigurationAsync(String address, IDocumentRetriever retriever, CancellationToken cancel)
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
   --- End of inner exception stack trace ---
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync()
   at Microsoft.Identity.Web.Resource.AadIssuerValidator.GetIssuerValidator(String aadAuthority)
   at Eds.Platform.Identity.ServiceCollectionExtensions.<>c__DisplayClass0_0.<AddClientAuthentication>b__1(JwtBearerOptions options)
   at Microsoft.Extensions.Options.ConfigureNamedOptions`1.Configure(String name, TOptions options)
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.OptionsMonitor`1.<>c__DisplayClass11_0.<Get>b__0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Microsoft.Extensions.Options.OptionsCache`1.GetOrAdd(String name, Func`1 createOptions)
   at Microsoft.Extensions.Options.OptionsMonitor`1.Get(String name)
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.InitializeAsync(AuthenticationScheme scheme, HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationHandlerProvider.GetHandlerAsync(HttpContext context, String authenticationScheme)
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
'testhost.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.12\Microsoft.AspNetCore.Http.Extensions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware: Error: An exception was thrown attempting to execute the error handler.
```

**Expected behavior**

Application must be resilient to AAD endpoint unavailability at as early startup point as this one.

**Comment by jmprieur** [comment] 2021-03-02 08:07
@abatishchev 
- This is not a Microsoft.Identity.Web issue (it uses Microsoft.AspNetCore.Authentication.AzureAD.UI 3.1.10), but an ASP.NET one.
- Having said that we (Identity) are working on resilience.

cc: @henrik-me

**Comment by abatishchev** [comment] 2021-03-02 18:19
hi Jean-Marc, ah you're right. sorry about this. it was a late hour, AAD PPE was down for all 1P customers. I rushed to open an issue after searching for the methods in the exception stack trace and finding this repo.

@jmprieur, @henrik-me shall I open an issue in the ASP.NET repo instead?

**Comment by jmprieur** [comment] 2021-03-03 15:08
yes, you could. but we are working on something, but this will take some time. 
We'd update Microsoft.Identity.Web

**Comment by cvbc2010** [comment] 2021-03-08 12:26
i was able to fix this adding 
services.AddHttpClient("ProxyClient", c =>
            {
                //c.BaseAddress = new Uri(Configuration.GetValue<string>("AccountURL"));
                // Account API ContentType
                c.DefaultRequestHeaders.Add("Accept", "application/json");
            }).ConfigurePrimaryHttpMessageHandler(() =>
            {
                var proxySettings = new ProxySettings();
                Configuration.GetSection("AppSettings:ApiSettings:WebProxySettings").Bind(proxySettings);
                return new HttpClientHandler()
                {
                    UseProxy = true,
                    ServerCertificateCustomValidationCallback = HttpClientHandler.DangerousAcceptAnyServerCertificateValidator,
                    Proxy = this.getProxy(proxySettings.Url, proxySettings.PortNumber, proxySettings.UserName, proxySettings.Password)
                };
            });

services.Configure<AadIssuerValidatorOptions>(options => {
                options.HttpClientName = "ProxyClient";
            });

but now i am getting an error while retrieving token as i need to provide proxy credentials for token aquisition.

**Comment by jmprieur** [comment] 2021-03-08 14:19
@cvbc2010 :  did you also see https://github.com/AzureAD/microsoft-identity-web/wiki/1.2.0#support-for-back-channel-proxys-for-the-issuer-validator-metadata ?

**Comment by cvbc2010** [comment] 2021-03-09 06:25
Yes I have checked this. and implemented the same as above. 
But my issue is I need to retrieve token via proxy server with credentials.
Enable EnableTokenAcquisitionToCallDownstreamApi should have an overloaded version which take HttpNamedClient name as parameter.

**Comment by jmprieur** [comment] 2021-03-09 10:35
Thanks for the update @cvbc2010 
I guess this is a dupe of https://github.com/AzureAD/microsoft-identity-web/issues/891?

**Closed** 2021-12-23 02:04 UTC
Labels: duplicate, enhancement, external
