### ISSUE TITLE
Ability to set Request headers for IDownStreamWebAPI  

### ISSUE THREAD

**Issue by parwejp** [AzureAD/microsoft-identity-web#1063] opened 2021-03-15 13:40 UTC
Dear Team,

I am not able to find out how to send request headers while using get requests on iDownStreamWebAPI. I recently got an error while calling MS graph api to add "ConsistencyLevel = eventual" header.

[Microsoft Graph advanced queries Header](https://developer.microsoft.com/en-us/identity/blogs/microsoft-graph-advanced-queries-for-directory-objects-are-now-generally-available/)

**Describe alternatives you've considered**
Have switched to ITokenAquisition implementation for now but would be nice to use IDownStreamWebAPI for it. As @rollandjb mentioned [here](https://github.com/AzureAD/microsoft-identity-web/issues/503#issuecomment-687824082) would be possible to set request headers with pooled HttpClient with proper isolation. I am no expert but creating HttpRequestMessage could be quick fix.

If it is implemented already, could you please be kind enough to point me out to documentation?

@jennyf19 : Created the feature request as requested.

**Comment by jmprieur** [comment] 2021-06-03 11:16
MSAL.NET 4.32.0 now supports `WithExtraHttpHeaders` on AcquireTokenXXX

**Comment by parwejp** [comment] 2021-06-03 12:58
Perfect. Thanks.

**Comment by jmprieur** [comment] 2021-06-03 13:03
@parwejp reopening because although this is supported by MSAL.NET, we still need to add support in Microsoft.Identity.Web

**Comment by jmprieur** [comment] 2021-06-07 14:33
Proposal:
- In `TokenAcquisitionOptions`, add a new `ExtraHttpHeaders` of type [`IHeaderDictionary`] that will be passed-in to the calls to MSAL.NET (using `WithExtraHttpHeaders`)
- In `DownstreamWebApiOptions`, add a new member `ExtraHttpHeaders` of type [`IHeaderDictionary`](https://docs.microsoft.com/dotnet/api/microsoft.aspnetcore.http.iheaderdictionary?view=aspnetcore-5.0). This will be used to add headers to the HttpRequest used to call the web API

Note that the two properties apply to different calls: the first during the token acquisition, and the second for the web API.

**Comment by jguldal** [comment] 2021-10-07 21:02
Is there any workaround for adding HTTP headers to the downstream request? Open for anything really, we really need this feature...

**Comment by jennyf19** [comment] 2021-12-23 02:05
Duplicate of #891

**Comment by jennyf19** [comment] 2022-01-08 03:23
Included in the [1.22.0 release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/1.22.00

**Closed by jennyf19** 2022-01-08 03:23 UTC
Labels: enhancement, Spec'd, ADAL-to-MSAL-migration-blocker

**Comment by jmprieur** [comment] 2022-01-08 05:59
The documentation is [Customizing the headers (or the HttpMessageRequest) when using IDownstreamWebApi](https://github.com/AzureAD/microsoft-identity-web/wiki/adding-call-api-to-web-app#customizing-the-headers-or-the-httpmessagerequest-when-using-idownstreamwebapi)
