### ISSUE TITLE
Allow specifying Authentication scheme display name

### ISSUE THREAD

**Issue by wmmihaa** [AzureAD/microsoft-identity-web#974] opened 2021-02-16 12:31 UTC
A button that says "OpenIdConnect" does not mean much to end users, and it would be great if we could set the DisplayName property in the configuration to better present the intention of clicking the button. For instance "Using your Microsoft.com account".

In a related issue (#971) we need to provide multiple AAD options for users to log in with, in which case having five buttons saying "OpenIdConnect" make no sense.

**Comment by jmprieur** [comment] 2021-02-17 08:01
@wmmihaa. Thanks for raising.
This is a duplicate of https://github.com/AzureAD/microsoft-identity-web/issues/808
(closing as such)

**Closed by jmprieur** 2021-02-17 08:01 UTC
Labels: duplicate, enhancement

**Comment by jmprieur** [comment] 2021-02-17 08:02
BTW, we have started an experimental branch: https://github.com/AzureAD/microsoft-identity-web/tree/jmprieur/IdentityProviderName
But we have other hi pri work at the moment, so this is in standby
