### ISSUE TITLE
[Bug] Prevent app developers from using DistributedMemoryCache in production applications

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-identity-web#1616] opened 2022-01-31 15:44 UTC
**Which version of Microsoft Identity Web are you using?**
1.22.0

**Expected behavior**
Apps should configure either L1 cache or L1+L2 cache where L2 is not DistributedMemoryCache.

**Actual behavior**
Our documentation is not clear enough and many apps use L1 + L2 caching where L2 is DistributedMemoryCache.

The problem with this approach is that both L1 (MemoryCache) and L2 (DistributedMemoryCache) end up using  `MemoryCache` object internally to store data. So this results in having 2 `MemoryCache` objects with the same data. 

As per https://docs.microsoft.com/en-us/aspnet/core/performance/caching/distributed?view=aspnetcore-6.0#distributed-memory-cache apps should not use `DistributedMemoryCache` in production. It's just a simple default.

**Possible solution**
Log errors when L2 cache is set to `DistributedMemoryCache`

**Comment by jmprieur** [comment] 2022-01-31 16:42
Doc updated by this PR (from Bogdan): https://github.com/MicrosoftDocs/azure-docs/pull/87209

**Comment by jmprieur** [comment] 2022-01-31 16:43
Would be better done by a static analyzer.
We are not going to log an error, we would not have a clean way to detect the implementation as Microsoft.Identity.Web does not depend on the implementations, only on the IDistributedCache interface. Only apps depend on the implementations.

**Comment by bgavrilMS** [comment] 2022-01-31 16:59
The whole point of `MemoryDistributedCache` is that it ships in the box. It's in the same assembly and namespace as `IDistributedCache`. 

![image](https://user-images.githubusercontent.com/12273384/151838369-dfda13b3-5954-4a3c-bb07-2ced0a5c22db.png)

**Comment by jmprieur** [comment] 2022-01-31 17:07
I see, my bad.
Go ahead, then

**Comment by jmprieur** [comment] 2022-01-31 17:07
It's not a bug, though. I disagree with that aspect

**Comment by bgavrilMS** [comment] 2022-01-31 17:15
Today, the library does the following: 

```csharp
            services.AddDistributedMemoryCache();
            services.AddSingleton<IMsalTokenCacheProvider, MsalDistributedTokenCacheAdapter>();
```

So we're injecting the default, non-production friendly `IDistributedCache` alongside the L1 memory cache. We treat "bad" defaults as bugs generally, as they can cause production issues in the long run. If we didn't have to care about backwards compat, I'd modify this as: 

```csharp
            services.AddSingleton<IMsalTokenCacheProvider, MsalDistributedTokenCacheAdapter>();

          // and later
         if (distributedCache is null) 
               throw new Nice_Exception();
```

**Comment by jmprieur** [comment] 2022-01-31 17:21
It should not be the default.

**Comment by bgavrilMS** [comment] 2022-01-31 17:42
Wouldn't that be a breaking change @jmprieur ?

**Comment by jmprieur** [comment] 2022-01-31 18:29
yes, it would.

**Comment by jennyf19** [comment] 2023-02-28 03:35
We haven't seen more reports of this being an issue. Closing for now.

**Closed by jennyf19** 2023-02-28 03:35 UTC
Labels: bug, documentation, P2, token cache serialization - distributed cache, static analysis
