### ISSUE TITLE
[Bug] In Blazor web assembly applications, MicrosoftIdentityConsentAndConditionalAccessHandler.ChallengeUser() does not pass login_hint to AAD

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-identity-web#750] opened 2020-11-05 16:54 UTC
**Which version of Microsoft Identity Web are you using?**
Latest

**Where is the issue?**
* Blazorwasm

```CSharp
      try
        {
            if (!ConsentHandler.User.Claims.Any(c => c.Type == "requestedClaimsType" && c.Value == "requestedClaimsValue"))
            {
                ConsentHandler.ChallengeUser(new string[] { "scopes" }, claimsToRequest);
                return;
            }

            token = await TokenAcquisitionService.GetAccessTokenForUserAsync(new string[] { "user.read" })
                    .ConfigureAwait(true);
            // get authenticatin result for user -- gives sub-error code "classification"
        }
        catch (Exception ex)
        {
            ConsentHandler.HandleException(ex);
        }
```

**Expected behavior**
Given that `ConsentHandler.ChallengeUser` passes the login_hint it should be received by Azure AD

**Actual behavior**
The login_hint is not received by Azure AD.

**Comment by jennyf19** [comment] 2020-11-06 00:52
Duplicate of this [issue](https://github.com/dotnet/aspnetcore/issues/19925) in asp net.

**Comment by jennyf19** [comment] 2020-11-06 00:53
Closing as the fix is w/asp .net

**Closed by jennyf19** 2020-11-06 00:53 UTC
Labels: duplicate, external
