### ISSUE TITLE
[Bug] No Incremental Consent/Redirects when using AddMicrosoftIdentityWebApp

### ISSUE THREAD

**Issue by iUnknwn** [AzureAD/microsoft-identity-web#570] opened 2020-09-12 00:57 UTC
**Which version of Microsoft Identity Web are you using?**
Note that to get help, you need to run the latest version. 
0.4.0-preview

**Where is the issue?**
* Web app
    * [ ] Sign-in users
    * [x] Sign-in users and call web APIs
* Web API
    * [ ] Protected web APIs (validating tokens)
    * [ ] Protected web APIs (validating scopes)
    * [ ] Protected web APIs call downstream web APIs
* Token cache serialization
     * [x] In-memory caches
     * [ ] Session caches
     * [ ] Distributed caches
* Other (please describe)

**Is this a new or an existing app?**
c. This is a new app or an experiment.

**Repro**
When writing an app that can be interacted with either via a user (visiting Razor pages), or a program (using WebAPI controllers), there is an odd problem where, when this format of configuration is used:

```csharp
 services.AddAuthentication()
                .AddMicrosoftIdentityWebApp(Configuration, "AzureAd", "OpenIdConnect")
                .EnableTokenAcquisitionToCallDownstreamApi(initialScopes: new string[] { "user.read", "https://app.vssps.visualstudio.com/user_impersonation" })
                .AddInMemoryTokenCaches();
```

Then all incremental consent steps will fail (and certain pages AuthorizeForScopes for the Visual Studio permission will simply not load with a 401). 

However, if that is modified to:

```csharp
services.AddMicrosoftIdentityWebAppAuthentication(Configuration, "AzureAd", "OpenIdConnect")
                .EnableTokenAcquisitionToCallDownstreamApi(initialScopes: new string[] { "user.read", "https://app.vssps.visualstudio.com/user_impersonation" })
                .AddInMemoryTokenCaches();
```

Then redirects work as expected.

For context, here's a full ConfigureServices function:

```csharp
        public void ConfigureServices(IServiceCollection services)
        {

            services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
                .AddMicrosoftIdentityWebApi(Configuration, "AzureAd");

            services.AddMicrosoftIdentityWebAppAuthentication(Configuration, "AzureAd", "OpenIdConnect")
                .EnableTokenAcquisitionToCallDownstreamApi(initialScopes: new string[] { "user.read", "https://app.vssps.visualstudio.com/user_impersonation" })
                .AddInMemoryTokenCaches();

            services.AddRazorPages().AddMicrosoftIdentityUI();
            services.AddControllers();

            services.AddAuthorization(options =>
            {
                options.FallbackPolicy = new AuthorizationPolicyBuilder(
                    JwtBearerDefaults.AuthenticationScheme,
                    "OpenIdConnect")
                    .RequireAuthenticatedUser()
                    .Build();
            });
        }
```

**Expected behavior**
Both methods should have the same behavior. 

**Actual behavior**
When using one method (AddMicrosoftIdentityWebApp) the application no longer redirects for authentication when it is needed.

**Comment by jennyf19** [comment] 2020-09-13 21:07
@iUnknwn You cannot request scopes for different resources in the same call (this is an Azure AD constraint). So you would need to do `.EnableTokenAcquisitionToCallDownstreamApi()` for one of the resources, like `"user.read"`, and then request the other in the controller. Or you can do admin consent for your application in the portal, which means there will not be user consent.
[More info here on managing consent](https://github.com/AzureAD/microsoft-identity-web/wiki/Managing-incremental-consent-and-conditional-access).
cc: @jmprieur

**Comment by iUnknwn** [comment] 2020-09-14 18:08
Hi @jennyf19 - thank you for the explanation. Just to follow up, though - regardless of what scopes are requested, is it expected that, in this case, `AddMicrosoftIdentityWebAppAuthentication` work correctly (and incremental consent works), but `AddMicrosoftIdentityWebApp` fails to insert redirects? If so, can you explain the differences between the calls?

**Comment by jennyf19** [comment] 2020-09-14 20:03
@iUnknwn that's because the default scheme is getting overridden, and there can only be one. This [documentation](https://github.com/azuread/microsoft-identity-web/wiki/web-apis#using-multiple-authentication-schemes) shows how to handle multiple schemes, more info in [asp .net](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/limitingidentitybyscheme?view=aspnetcore-3.1). This should work.

**Comment by iUnknwn** [comment] 2020-09-16 23:57
Sorry - I still think I'm missing something. If I have an application that has some protected web apis (a /api endpoint), and a normal website that a user loads, both which need to be protected via OAuth, what is the correct way to mix a `WebApp` and `WebAPI` authentication scheme? The documentation you linked to covers multiple WebAPI providers, but not mixing types. 

As I mentioned, from what I can tell mixing `AddMicrosoftIdentityWebAppAuthentication` with `AddMicrosoftIdentityWebApi` works, but mixing `AddMicrosoftIdentityWebApi` with `AddMicrosoftIdentityWebApp` does not.

**Comment by jmprieur** [comment] 2020-09-23 08:30
Duplicate of https://github.com/AzureAD/microsoft-identity-web/issues/547

@iUnknwn did you decorate the [Authorize] attribute for your HTML pages (Web app) and your api pages (web api) with the scheme ? did you read this article? [Authorize with a specific scheme in ASP.NET Core](https://docs.microsoft.com/aspnet/core/security/authorization/limitingidentitybyscheme)

**Comment by jmprieur** [comment] 2020-10-08 18:16
Closing as this seems answered.
@iUnknwn feel free to reopen if you disagree

**Closed by jmprieur** 2020-10-08 18:16 UTC
Labels: answered, question
