### ISSUE TITLE
[Bug] DefaultCertificateLoader does not accept that name : LocalComputer

### ISSUE THREAD

**Issue by brentschmaltz** [AzureAD/microsoft-identity-web#1702] opened 2022-04-11 05:34 UTC
**Which version of Microsoft Identity Web are you using?**
master

To repo:
1. Create a CertificateDescription with CertificateStorePath = "LocalComputer/My".
2. Try and load the cert.

The error has the following message:

IDW10703: Certificate store path must be of the form 'StoreLocation/StoreName'. StoreLocation must be one of 'CurrentUser', '**CurrentMachine**'. StoreName must be empty or one of 'AddressBook', 'AuthRoot', 'CertificateAuthority', 'Disallowed', 'My', 'Root', 'TrustedPeople', 'TrustedPublisher'. 

If you open up MMC the common names are: "CurrentUser" and "LocalComputer"
Since you already have support for "CurrentMachine", please add support for "LocalComputer".

See this [document ](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.x509certificates.x509store.location?view=net-6.0)for names.

I is always a good idea to echo what was received.
The above error message could be written"
IDW10703: The Certificate store path received '.......' was not of the form....

**Comment by jennyf19** [comment] 2022-04-11 16:34
@brentschmaltz Not sure what the issue is. We are parsing the values out [here](https://github.com/AzureAD/microsoft-identity-web/blob/b31140ff2d7478c86ef668edca3164aa7fd6846c/src/Microsoft.Identity.Web.Certificate/DefaultCertificateLoader.cs#L291), and using CurrentUser as the default.

The only values for StoreLocation are CurrentUser and LocalMachine:
<img width="734" alt="image" src="https://user-images.githubusercontent.com/19942418/162787536-aaa2db93-f516-4db9-a566-74e48a431271.png">

**Comment by brentschmaltz** [comment] 2022-04-13 15:37
@jennyf19 there is no 'CurrentMachine'. Your error message, IDW10703, includes the name: 'CurrentMachine', it should be 'LocalMachine'.

**Comment by jennyf19** [comment] 2022-04-13 23:35
@brentschmaltz That's not what the issue says above, but thanks for clarifying. Will fix the error message.

**Comment by jennyf19** [comment] 2022-04-14 00:15
fixed in #1704

**Comment by brentschmaltz** [comment] 2022-04-14 15:20
@jennyf19 thanks for fixing, when i wrote the bug i was confused because of the error message.
Your explanation helped me understand what the issue was.
Sorry for the confusion.

**Comment by jennyf19** [comment] 2022-04-14 15:43
@brentschmaltz it's fine! I was confused too so thanks for the explanation. I'll re-open until we release the updated message and then close.

**Comment by jennyf19** [comment] 2022-04-20 02:51
Released in [1.24.0](https://github.com/AzureAD/microsoft-identity-web/releases/tag/1.24.0).

**Closed by jennyf19** 2022-04-20 02:51 UTC
Labels: documentation, fixed
