### ISSUE TITLE
[Bug]  The response has already started, the error page middleware will not be executed on Scope Validation

### ISSUE THREAD

**Issue by ArnaudChirat** [AzureAD/microsoft-identity-web#771] opened 2020-11-17 16:59 UTC
**Which version of Microsoft Identity Web are you using?**
Note that to get help, you need to run the latest version. 
Microsoft Identity Web 1.3.0

**Where is the issue?**
* Web app
    * [ ] Sign-in users
    * [ ] Sign-in users and call web APIs
* Web API
    * [ ] Protected web APIs (validating tokens)
    * [x] Protected web APIs (validating scopes)
    * [ ] Protected web APIs call downstream web APIs
* Token cache serialization
     * [ ] In-memory caches
     * [ ] Session caches
     * [ ] Distributed caches
* Other (please describe)

**Is this a new or an existing app?**
c. This is a new app or an experiment.

**Repro**

```csharp
static readonly string[] scopeRequiredByApi = new string[] { "access_user" };
public async Task<IActionResult> GetCode()
{
    HttpContext.VerifyUserHasAnyAcceptedScope(scopeRequiredByApi);
    ...
}

```

**Expected behavior**
When sending a scp not present in scopeRequiredApi get an 403 Forbidden with the scope required

**Actual behavior**
Get an error 403 but with a "transfer closed with outstanding read data remaining"

**Possible solution**

**Additional context / logs / screenshots**
get this log
!!! IDW10203: The 'scope' or 'scp' claim does not contain scopes 'access_user' or was not found. 
warn: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[2]
      The response has already started, the error page middleware will not be executed.
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HM4B2V3F5PUR", Request id "0HM4B2V3F5PUR:00000002": An unhandled exception was thrown by the application.

**Comment by jennyf19** [comment] 2020-11-17 19:55
@ArnaudChirat do you mind trying this [branch](https://github.com/AzureAD/microsoft-identity-web/tree/jennyf/scopeVal) to see if it resolves your issue? Thanks.

**Comment by ArnaudChirat** [comment] 2020-11-18 08:44
@jennyf19 Thank you very much, it works perfectly

**Comment by jennyf19** [comment] 2020-11-24 17:01
@ArnaudChirat I'm not sure what the problem is...is it the error message?

**Comment by jennyf19** [comment] 2020-11-24 17:07
also, @ArnaudChirat, are you in developer mode?

**Comment by jennyf19** [comment] 2020-12-02 22:21
Hi @ArnaudChirat, not sure if you saw the above, but wondering if you are in developer mode...thanks.

**Comment by jennyf19** [comment] 2020-12-18 17:13
closing, but feel free to reopen @ArnaudChirat

**Closed by jennyf19** 2020-12-18 17:13 UTC
Labels: In progress, P2, bug, more info needed

**Comment by jwdsalim** [comment] 2022-10-13 04:45
- [ ] 

- [ ] 

- [ ]    ##@gfgfgfgfg``
