### ISSUE TITLE
B2C password reset fails for confidential client not configured to support implicit flow

### ISSUE THREAD

**Issue by rollandjb** [AzureAD/microsoft-identity-web#756] opened 2020-11-10 14:32 UTC
**Which version of Microsoft Identity Web are you using?**
Note that to get help, you need to run the latest version. 
Microsoft Identity Web 1.2.0

**Where is the issue?**
* Web app
    * [x] Sign-in users
    * [ ] Sign-in users and call web APIs
* Web API
    * [ ] Protected web APIs (validating tokens)
    * [ ] Protected web APIs (validating scopes)
    * [ ] Protected web APIs call downstream web APIs
* Token cache serialization
     * [ ] In-memory caches
     * [ ] Session caches
     * [ ] Distributed caches
* Other (please describe)

**Is this a new or an existing app?**
App under development

**Repro**

- Configure an application in B2C which does **not** support implicit flow
- Use `dotnet new webapp --auth IndividualB2C` to scaffold app, updating package references to 1.2.0
- Configure with B2C application defined above (clientId and secret)
- include `<a href="/MicrosoftIdentity/Account/signin/OpenIdConnect">Sign In</a>` in `index.html`
- Set logging at `Debug` level
- Run app and click link
- Click `Forgot Your Password?

**Expected behavior**
The B2C Reset Password screen

**Actual behavior**
Debug output reporting ` error: 'unauthorized_client', error_description: 'AADB2C90057: The provided application is not configured to allow the 'OAuth' Implicit flow.`

**Possible solution**
- The problem is that the `authorize` call to the password reset policy includes `id_token` in `ResponseType`, whereas the signupsignin policy does not.

- Enabling implicit flow does provide a workaround, but this is undesirable given that that the implicit flow is disappearing.

**Additional context / logs / screenshots**
Add any other context about the problem here, such as logs and screenshots.

**Comment by jmprieur** [comment] 2020-11-10 14:51
This is by design: https://github.com/AzureAD/microsoft-identity-web/blob/00fc7c31f915ecde4fcf7131c0d00ff921a27b47/src/Microsoft.Identity.Web/AzureADB2COpenIDConnectEventHandlers.cs#L46

Last time I checked, a few weeks ago, this was not working for the b2C case without the id token. Do you think this works now, @rollandjb ?
cc: @jennyf19

**Comment by rollandjb** [comment] 2020-11-11 08:05
@jmprieur, @jennyf19  It does work just providing `code`. This is what I did

1. I added the following in startup

```csharp
            services.Configure<OpenIdConnectOptions>(OpenIdConnectDefaults.AuthenticationScheme, options => {

                var parentHandler = options.Events.OnRedirectToIdentityProvider;
                options.Events.OnRedirectToIdentityProvider = async (context) => {
                    Console.WriteLine("==> OnRedirectToIdentityProvider <==");

                    await parentHandler(context);

                    if (context.ProtocolMessage.IssuerAddress.Contains("PasswordReset", StringComparison.OrdinalIgnoreCase)) {
                        context.ProtocolMessage.ResponseType = "code";
                    }
                };
            });
```

2. I turned off Implicit Flow in AD B2C for this client

3. This is the call as per the developer tools network tab:

```
Query String Parameters
    ...
    response_type: code
    ...
```

I was able to change the password.

**Comment by jmprieur** [comment] 2020-11-11 09:12
Thanks @rollandjb 
Just another question. Is your web app calling downstream APIs? or just signing-in users?

**Comment by rollandjb** [comment] 2020-11-11 09:52
@jmprieur 

Yes it does call downstream APIs:

    .EnableTokenAcquisitionToCallDownstreamApi()

But I do not use `AddDownstreamWebApi`. I have a typed HTTP client that implements type-safe methods for accessing the endpoints of my REST server.

**Comment by jmprieur** [comment] 2020-11-12 10:04
Thanks for the update, @rollandjb
I see that you have the hypothesis that the policy will be named (or will contain) "PasswordReset".

It's my understanding that the names of the userflows/policies can be anything?

**Comment by jmprieur** [comment] 2020-11-12 10:13
@jennyf19 proposing to fix this one. In the [OnRedirectToIdentityProvider](https://github.com/AzureAD/microsoft-identity-web/blob/529c83fb902a008c6743fca3712b94aecf447eac/src/Microsoft.Identity.Web/AzureADB2COpenIDConnectEventHandlers.cs#L44) callback we should change the test to use code when the IssuerAddress.Contains(microsoftIdentityOptions.[ResetPasswordPolicyId](https://github.com/AzureAD/microsoft-identity-web/blob/6ad2b2439f7fef665b68defe2e1067cc5281f48f/src/Microsoft.Identity.Web/MicrosoftIdentityOptions.cs#L43))

**Comment by jennyf19** [comment] 2020-11-13 03:35
@jmprieur I think the fix should happen on the portal side. The actual issue is coming from their UI options.

**Comment by rollandjb** [comment] 2020-11-13 10:27
@jennyf19 According to OAuth2.1, implicit flow will **not** be supported in the future, which means (as I understand it) tokens can not be requested from the authorise endpoint, but must be obtained by exchanging the `code` for tokens at the token endpoint.

In the meantime, by turning off `implicit flow` on B2C, those of us performing authentication via confidential clients ensure that **only** `code flow` can be used.

**Comment by jmprieur** [comment] 2020-11-13 10:37
@rollandjb this is **not** implicit flow
This is using **hybrid**: `response_type=id_token+code`. That’s pretty standard, and lets you paint the page with user info from the id token before they redeem the code for access tokens. 

The fact that the portal has it in a category named "implicit flow" is confusing. When you check "implicit flow access token", you get the implicit flow, not when you check id token only.

That said:
- we are going to make sure that `code` can be accepted by the B2C service for all flows (it's only accepted for the ResetPassword policy for the moment, not for SUSI for instance)
- we also want to have the portal be more precise.

**Comment by rollandjb** [comment] 2020-11-13 10:53
@jmprieur Thanks for the clarification on implicit vs hybrid.

I don't understand your point about `code` not being accepted by SUSI. In my app the `authorise` call 

`https://xxx.b2clogin.com/xxx.onmicrosoft.com/b2c_1a_signupsignin/oauth2/v2.0/authorize?`

the query parameters are:

```
client_id: ---
redirect_uri: https://localhost:5001/signin-oidc
response_type: code
scope: openid profile offline_access <custom_scope>
response_mode: form_post
nonce: ---
client_info: 1
x-client-brkrver: IDWeb.1.2.0.0
state: ---
x-client-SKU: ID_NETSTANDARD2_0
x-client-ver: 6.7.1.0
```

**Comment by jmprieur** [comment] 2020-11-13 11:15
@rollandjb does it work if you remove .EnableTokenAcquisitionToCallDownstreamApi() ?

**Comment by rollandjb** [comment] 2020-11-13 11:40
@jmprieur if I do that, then my app won't start because it cannot resolve `Microsoft.Identity.Web.ITokenAcquisition` which I need in the `HttpMessgeHandler` of my typed HttpClient, where I add the access token (using `ITokenAcquisition`) to the `Authorization` header.

Anything else you'd like me to try?

**Comment by jmprieur** [comment] 2020-11-13 13:33
@rollandjb : did you try to use Edit profile, and then access to your web api? (this does not work for me without idtoken_token

**Comment by rollandjb** [comment] 2020-11-13 15:34
@jmprieur I am able to edit profile. I check for edit profile policy in OnRedirectToIdentityProvider event and remove `id_token`.

I **am** being redirected to MicrosoftIdentity/Account/Error afterwards, but I haven't found out yet why. I will look into it and let you know.

Just note that we do not use an Edit Profile policy—we have no need for it so far. We also use custom policies, so I had to add a new user flow to try this out. The error may have something to do with that.

I will get back to you, probably on Monday.

**Comment by jmprieur** [comment] 2020-11-13 15:53
Thanks @rollandjb for the update.

**Comment by rollandjb** [comment] 2020-11-14 12:24
@jmprieur 

My server hosts a SPA in `wwwroot` which calls the downstream API via a reverse proxy service (currently `ProxyKit`) which is configured to add the bearer token to the request using an `HttpMessageHandler` and `ITokenAcquisition ` as described above.

Thus calls by the SPA to the downstream API are secured by the session cookie returned on successful B2C authentication.

> The` SPA` I am using to test with is just a single `index.html` file, containing links for
> - `Sign In` or `Sign Out`, depending on authentication status of the user, detected by trying to call the downstream API
> - `Edit Profile` to change the user's information on B2C (for testing)
> - A link to fetch some JSON data from the downstream API
> 
> Nothing fancy.

B2C has "implicit flow" turned off (i.e. cannot request `response_type` containing `id_token` or `token`

Server is configured to remove `id_token` from `response_type` using events.

## Sign In

- Ensure user is not authenticated
- User clicks link `<a href="/MicrosoftIdentity/Account/SignIn">Sign In</a>`
- Browser receives session cookie it will pass in all calls to API
- [x] All good

## Edit Profile

- User clicks link `<a href="/MicrosoftIdentity/Account/EditProfile">Edit Profile</a>`
- `EditProfile` action executes `SignUpSignInPolicyId` flow to sign user in, if not authenticated 
- Server sends `authorize` request to EditProfile flow with `response_type=code`
- B2C displays Profile Edit UI and user edits info
- Server receives `code`
- Server attempts to exchange `code` for token(s) at token endpoint of `SignUpSignInPolicyId`
   - Fails with `invalid_grant` error because `code` is for`EditProfilePolicyId`

> The user **is** authenticated, but the associated access token will **not** contain any updated claims based on the user B2C information

## Reset Password

In my example, the user can only reach the `Forgot your password?` link if they are not authenticated (via `SignUpSignInPolicyId`).

As for `Edit Profile`, the server receives a `code` that is not valid for `SignUpSignInPolicyId` token endpoint.

Thus the user is left unauthenticated after changing their password. Some might even say this is appropriate.

## Summary

So, in summary, with B2C "implicit flow" turned off, requesting `response_type=code` on `EditProfilePolicyId` and `ResetPasswordPolicyId` **does** allow the user to perform the respective functions. However, they are not authenticated against those flows. To achieve that, the relationship between flows and `code` would need to be tracked.

Each custom flow (policy) in B2C declares precisely the claims to be returned in the JWT tokens. Not tracking the relationship between flows and `code` can be problematic.

Our clients (desktop, mobile and SPA) currently call our API directly, passing the bearer token they obtained using either implicit (!) or code/pkce. We have a number of B2C custom policies to facilitate different signup experiences and other functionality such as changing verified email. Each policy results in an access token. For code flow we have to remember which policy was used.

I want to move to a hosted solution for these clients to keep the access tokens more secure.

Thank you for your time. I hope this makes sense and is helpful.

**Comment by jmprieur** [comment] 2020-11-16 09:32
Thanks @rollandjb

**Comment by rollandjb** [comment] 2020-11-30 14:27
@jmprieur 

I now think I understand how  the hybrid flow, which obtains `id_token` and `code`, is used by `Microsoft.Identity.Web` to allow signin with different policies:

- If `id_token` is requested, then a `ClaimsPrinciple` is created with the `id_token` kv values as claims, and
- `AddAccountToCacheFromAuthorizationCodeAsync` https://github.com/AzureAD/microsoft-identity-web/blob/4ab0da4c93ef554fab397cb4f1a873ff62d392c3/src/Microsoft.Identity.Web/TokenAcquisition.cs#L124 (called from `onAuthorizationCodeReceived` event)  uses `GetUserFlowId` https://github.com/AzureAD/microsoft-identity-web/blob/4ab0da4c93ef554fab397cb4f1a873ff62d392c3/src/Microsoft.Identity.Web/TokenAcquisition.cs#L151 to read the `tfp` claim from the `ClaimsPrinciple`

So, the result is the user is logged in after `passwordReset` and `editProfile` with the claims provided by those flows, and the acquire token process uses the corresponding policy correctly.

**Comment by jmprieur** [comment] 2020-11-30 14:35
@rollandjb : proposing to close this issue.
(the fix of the explanations in the portal is under way)

Feel free to reopen if you disagree.

**Closed by jmprieur** 2020-11-30 14:35 UTC
Labels: enhancement, more info needed

**Comment by rollandjb** [comment] 2020-12-01 14:19
@jmprieur No need to reopen.

**Comment by jmprieur** [comment] 2020-12-16 13:44
To clarify the limitation: In Azure AD B2C, the oauth2AllowImplicitFlow (corresponding to the access token checkbox) controls whether Azure AD B2C token service will accept requests with either access token (and or) id token implicitly. So “access token” checkbox acts as if it controls both checkboxes in practice. The service team is aware if this, but there are no ETA on when they will fix this behavior
